### ISSUE TITLE
Bug Report (Quickstart) - docker-compose sample does not show table details

### ISSUE THREAD

**Issue by yohei1126** [amundsen-io/amundsen#1030]
## Expected Behavior

* Amundsen frontend should show table details

## Current Behavior

* Amundsen frontend just says "Something went wrong..."
* On Docker console, I found this error

```
amundsenfrontend    | 2021-05-01T08:49:01+0000.238 [ERROR] v0._get_table_metadata:149 (10:MainThread) - Encountered exception: {'columns': {0: {'col_type': ['Field may not be null.']}, 1: {'col_type': ['Field may not be null.']}, 2: {'col_type': ['Field may not be null.']}, 3: {'stats': {0: {'stat_type': ['Field may not be null.']}, 1: {'stat_type': ['Field may not be null.']}}, 'col_type': ['Field may not be null.']}}}
amundsenfrontend    | Traceback (most recent call last):
amundsenfrontend    |   File "/app/amundsen_application/api/metadata/v0.py", line 143, in _get_table_metadata
amundsenfrontend    |     results_dict['tableData'] = marshall_table_full(table_data_raw)
amundsenfrontend    |   File "/app/amundsen_application/api/utils/metadata_utils.py", line 109, in marshall_table_full
amundsenfrontend    |     table: Table = schema.load(table_dict).data
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 588, in load
amundsenfrontend    |     result, errors = self._do_load(data, many, partial=partial, postprocess=True)
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 711, in _do_load
amundsenfrontend    |     raise exc
amundsenfrontend    | marshmallow.exceptions.ValidationError: {'columns': {0: {'col_type': ['Field may not be null.']}, 1: {'col_type': ['Field may not be null.']}, 2: {'col_type': ['Field may not be null.']}, 3: {'stats': {0: {'stat_type': ['Field may not be null.']}, 1: {'stat_type': ['Field may not be null.']}}, 'col_type': ['Field may not be null.']}}}
amundsenfrontend    | 2021-05-01T08:49:01+0000.240 [DEBUG] action_log_callback.on_post_execution:70 (10:MainThread) - Calling callbacks: [<function logging_action_log at 0x7f35600818c0>]
amundsenfrontend    | 2021-05-01T08:49:01+0000.240 [DEBUG] action_log_callback.logging_action_log:85 (10:MainThread) - logging_action_log: ActionLogParams(command='_get_table_metadata', start_epoch_ms=1619858940889, end_epoch_ms=1619858941239, user='test@email.com', host_name='5ba94ec252fd', pos_args_json='[]', keyword_args_json='{"table_key": "dynamo://gold.test_schema/test_table2", "index": "0", "source": "search_results"}', output='{"tableData": {}, "msg": "Encountered exception: {\'columns\': {0: {\'col_type\': [\'Field may not be null.\']}, 1: {\'col_type\': [\'Field may not be null.\']}, 2: {\'col_type\': [\'Field may not be null.\']}, 3: {\'stats\': {0: {\'stat_type\': [\'Field may not be null.\']}, 1: {\'stat_type\': [\'Field may not be null.\']}}, \'col_type\': [\'Field may not be null.\']}}}", "status_code": 500}', error=None)
```

## Steps to Reproduce

1. Follow this instruction https://www.amundsen.io/amundsen/installation/
2. After running sample_data_loader.py access http://localhost:5000/
3. Input `test` on the input field then it shows table list
4. Click one of the list

## Screenshots (if appropriate)

<img width="499" alt="Screenshot 2021-05-01 at 16 51 34" src="https://user-images.githubusercontent.com/407811/116776863-830a2680-aa9d-11eb-8b4c-5c2e749d60f4.png">

## Your Environment

Amunsen version used: amundsen-frontend:1.0.5, amundsen-metadata:1.0.7, amundsen-search:1.1.1
Data warehouse stores: N/A
Deployment (k8s or native): Docker-compose
Link to your fork or repository: N/A

**Comment by yohei1126** [comment]
I also tried `sample_snowflake_data_loader.py` but found the same issue. 

```
amundsenfrontend    | Traceback (most recent call last):
amundsenfrontend    |   File "/app/amundsen_application/api/metadata/v0.py", line 143, in _get_table_metadata
amundsenfrontend    |     results_dict['tableData'] = marshall_table_full(table_data_raw)
amundsenfrontend    |   File "/app/amundsen_application/api/utils/metadata_utils.py", line 109, in marshall_table_full
amundsenfrontend    |     table: Table = schema.load(table_dict).data
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 588, in load
amundsenfrontend    |     result, errors = self._do_load(data, many, partial=partial, postprocess=True)
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 711, in _do_load
amundsenfrontend    |     raise exc
amundsenfrontend    | marshmallow.exceptions.ValidationError: {'columns': {0: {'stats': {0: {'stat_type': ['Field may not be null.']}, 1: {'stat_type': ['Field may not be null.']}, 2: {'stat_type': ['Field may not be null.']}, 3: {'stat_type': ['Field may not be null.']}, 4: {'stat_type': ['Field may not be null.']}}, 'col_type': ['Field may not be null.']}, 1: {'col_type': ['Field may not be null.']}, 2: {'col_type': ['Field may not be null.']}, 3: {'col_type': ['Field may not be null.']}, 4: {'stats': {0: {'stat_type': ['Field may not be null.']}, 1: {'stat_type': ['Field may not be null.']}, 2: {'stat_type': ['Field may not be null.']}}, 'col_type': ['Field may not be null.']}}}
```

**Comment by dorianj** [comment]
We recently pushed some fixes that should take care of this -- can you try the latest versions?
