### ISSUE TITLE
Not able to enable authentication in Mono repo

### ISSUE THREAD

**Issue by NiravLangaliya** [amundsen-io/amundsen#1074]
I am getting error when I have tired to enable authentication with mono repo code and without enabling authentication I am able to use all features of FE UI.

I have added logging trace at https://github.com/amundsen-io/amundsen/blob/4db357a266b244a3f1c176a86e1d2e5a262726ac/frontend/amundsen_application/models/user.py#L20 and I am able to get response back from my OIDC provide with token and user information and also user dict is getting formatted correctly but when call goes back to 

https://github.com/amundsen-io/amundsen/blob/4db357a266b244a3f1c176a86e1d2e5a262726ac/frontend/amundsen_application/api/v0.py#L30
https://github.com/amundsen-io/amundsen/blob/4db357a266b244a3f1c176a86e1d2e5a262726ac/frontend/amundsen_application/api/metadata/v0.py#L580

calling code , dict is not returning correct information and if I print it , it gives information like 

`Message: {'iat': ['Unknown field.'], 'ver': ['Unknown field.'], 'aud': ['Unknown field.'], 'at_hash': ['Unknown field.'], 'sub': ['Unknown field.'], 'auth_time': ['Unknown field.'], 'idp': ['Unknown field.'], 'exp': ['Unknown field.'], 'jti': ['Unknown field.'], 'iss': ['Unknown field.'], 'amr': ['Unknown field.']}`

Notes: 
Node version: 12 
NPM : 6
flaskoidc : 0.2.3
frontend: 3.7.0 

```
AttributeError: 'dict' object has no attribute 'user_id'
2021-05-11T08:15:16+0000.275 [INFO] _internal._log:113 (30858:Thread-15) - 10.30.204.27 - - [11/May/2021 08:15:16] "GET /api/auth_user HTTP/1.1" 500 -
2021-05-11T08:15:16+0000.461 [DEBUG] __init__._before_request:61 (30858:Thread-16) - Request Path: /api/metadata/v0/user/bookmark
2021-05-11T08:15:16+0000.461 [DEBUG] __init__._before_request:62 (30858:Thread-16) - Request Endpoint: metadata.get_bookmark
2021-05-11T08:15:16+0000.461 [DEBUG] __init__._before_request:63 (30858:Thread-16) - Whitelisted Endpoint: status,healthcheck,health
2021-05-11T08:15:16+0000.462 [INFO] user.load_user:24 (30858:Thread-16) - calling from models.user {'sub': '12utq5l37lhfgfgdfgd4GK0h8', 'email': 'Nirav.Langaliya@test.com', 'ver': 1, 'iss': 'https://test.okta.com/oauth2/auslkzh1o34sfRTVDRW7', 'aud': '0oawlwSDSR563kehk0h7', 'iat': 1620720909, 'exp': 1620724509, 'jti': 'ID.cdxPB9BS8JqrscAsdfeswr3312sdrewe35fOtGGomMe', 'amr': ['pwd'], 'idp': '0dsfd343439ochkKjK5r', 'auth_time': 1620720850, 'at_hash': '1D_LV86-amfK5dDmDFRES34'}
2021-05-11T08:15:16+0000.462 [INFO] user.load_user:25 (30858:Thread-16) - {'sub': '12utq5l37lhfgfgdfgd4GK0h8', 'email': 'Nirav.Langaliya@test.com', 'ver': 1, 'iss': 'https://test.okta.com/oauth2/auslkzh1o34sfRTVDRW7', 'aud': '0oawlwSDSR563kehk0h7', 'iat': 1620720909, 'exp': 1620724509, 'jti': 'ID.cdxPB9BS8JqrscAsdfeswr3312sdrewe35fOtGGomMe', 'amr': ['pwd'], 'idp': '0dsfd3423cQARE@chkKjK5r', 'auth_time': 1620720850, 'at_hash': '1D_LV86-amfK5dDmDFRES34'}
2021-05-11T08:15:16+0000.462 [INFO] user.load_user:34 (30858:Thread-16) - {'sub': '12utq5l37lhfgfgdfgd4GK0h8', 'email': 'Nirav.Langaliya@test.com', 'ver': 1, 'iss': 'https://test.okta.com/oauth2/auslkzh1o34sfRTVDRW7', 'aud': '0oawlwSDSR563kehk0h7', 'iat': 1620720909, 'exp': 1620724509, 'jti': 'ID.cdxPB9BS8JqrscAsdfeswr3312sdrewe35fOtGGomMe', 'amr': ['pwd'], 'idp': '0dsfd343439ochkKjK5r', 'auth_time': 1620720850, 'at_hash': '1D_LV86-amfK5dDmDFRES34', 'user_id': 'Nirav.Langaliya@test.com'}
2021-05-11T08:15:16+0000.462 [ERROR] v0.get_bookmark:608 (30858:Thread-16) - Encountered exception: 'dict' object has no attribute 'user_id'
Traceback (most recent call last):
  File "/home/ec2-user/python_venv_poc_v1/frontend/lib64/python3.6/site-packages/amundsen_frontend-3.7.0-py3.6.egg/amundsen_application/api/metadata/v0.py", line 580, in get_bookmark
    user_id = app.config['AUTH_USER_METHOD'](app).user_id
AttributeError: 'dict' object has no attribute 'user_id'
```

**Comment by PratikKhandelwal17** [comment]
```
ERROR:root:Encountered exception: 'NoneType' object has no attribute 'get'
amundsenfrontend    | Traceback (most recent call last):
amundsenfrontend    |   File "/app/amundsen_application/api/v0.py", line 26, in current_user
amundsenfrontend    |     user = app.config['AUTH_USER_METHOD'](app)
amundsenfrontend    |   File "/app/amundsen_application/oidc_config.py", line 35, in get_auth_user
amundsenfrontend    |     user_info = load_user(session.get("user"))
amundsenfrontend    |   File "/app/amundsen_application/models/user.py", line 24, in load_user
amundsenfrontend    |     if _str_no_value(user_data.get('user_id')):
amundsenfrontend    | AttributeError: 'NoneType' object has no attribute 'get'

```

I'm getting this error while trying to login using OIDC, please help

**Comment by jdkern11** [comment]
I feel you should post the solution to a GitHub issue on GitHub, not a link to a slack channel people need permission to access.

**Comment by meowsome** [comment]
I'm currently experiencing this issue when setting up an unmodified version of the latest Amundsen version with Keycloak authentication.
