### ISSUE TITLE
Bug Report: Update for new versions of SQLAlchemy for amundsendev/amundsen-metadata-oidc

### ISSUE THREAD

**Issue by iamtodor** [amundsen-io/amundsen#1157]
The issue relates to this one: https://github.com/pallets/flask-sqlalchemy/issues/910

Steps to reproduce:

[1]. ` docker run -it amundsendev/amundsen-metadata-oidc bash`
[2]. `python3 metadata_service/metadata_wsgi.py` (as we run it via Docker https://github.com/amundsen-io/amundsen/blob/37b6ea88f08b4ad233d6ece9256a23989abfe52a/metadata/public.Dockerfile#L14 )
[3]. Observe the following output:
```
Using requested Flask module flaskoidc and class FlaskOIDC
Traceback (most recent call last):
  File "metadata_service/metadata_wsgi.py", line 14, in <module>
    or 'metadata_service.config.LocalConfig')
  File "/usr/local/lib/python3.7/site-packages/metadata_service/__init__.py", line 72, in create_app
    app = class_obj(__name__, **flask_kwargs_dict)
  File "/usr/local/lib/python3.7/site-packages/flaskoidc/__init__.py", line 107, in __init__
    _session.app.session_interface.db.create_all()
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 555, in get_engine
    options = self.get_options(sa_url, echo)
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 914, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute
```
[4].  Find SQLAlchemy version

```
root@cc493499efe5:/app# pip freeze | grep SQL
Flask-SQLAlchemy==2.4.4
SQLAlchemy==1.4.15
```

Proposed solution: 
keep `SQLAlchemy==1.3.23` as it's done in Amundsen Frontend' requirements: https://github.com/amundsen-io/amundsen/blob/main/frontend/requirements.txt#L67

Please, point me out to the public Dockerfile for the container https://hub.docker.com/r/amundsendev/amundsen-metadata-oidc. I'll make a fixed pull request

**Comment by iamtodor** [comment]
This issue relates to the following question: https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1621950319110100

**Comment by iamtodor** [comment]
Could you please guys take a look? @mgorsk1 @feng-tao

**Comment by iamtodor** [comment]
@feng-tao is there something that depends on me to push this update to the docker container https://hub.docker.com/r/amundsendev/amundsen-metadata-oidc ? 
What is your regular workflow to deliver the code to the docker hub?
cc @verdan
