### ISSUE TITLE
Upgrading Atlas Entity Definitions Fails

### ISSUE THREAD

**Issue by lmk-coles** [amundsen-io/amundsen#1313]
## Expected Behavior
The entity definitions used by Amundsen in Apache Atlas should be updated via the databuilder types code.

## Current Behavior
There are a number of errors from Atlas, namely that "Attribute delete not supported".

## Possible Solution
This seems to be a limitation of Atlas...

## Steps to Reproduce

1. Using `amundsenatlastypes` 0.0.13, create the entity definitions in Atlas
2. Using the databuilder atlas types from amundsen repository (latest git), create the entity definitions in Atlas
3. There will be numerous failures

## Screenshots (if appropriate)
```
2021-07-06 00:43:04,917 databuilder.types.atlas INFO     Trying to create Column Entity                                                                                                                            
2021-07-06 00:43:04,954 databuilder.types.atlas INFO     Already Exists, updating Column Entity
2021-07-06 00:43:28,946 databuilder.types.atlas INFO     Applied Column Entity Definition
2021-07-06 00:43:28,946 databuilder.types.atlas INFO     Trying to create Reader Entity
2021-07-06 00:43:28,954 databuilder.types.atlas INFO     Already Exists, updating Reader Entity
2021-07-06 00:43:29,010 databuilder.types.atlas WARNING  Error updating Reader Entity.
Traceback (most recent call last):
  File "/home/lucas/amundsen/databuilder/databuilder/types/atlas/__init__.py", line 47, in create_or_update
    self.driver.typedef.create_atlas_typedefs(AtlasTypesDef(attrs=typedef_dict))
  File "/home/lucas/amundsen/databuilder/venv/lib/python3.8/site-packages/apache_atlas/client/typedef.py", line 116, in create_atlas_typedefs
    return self.client.call_api(TypeDefClient.CREATE_TYPE_DEFS, AtlasTypesDef, None, types_def)
  File "/home/lucas/amundsen/databuilder/venv/lib/python3.8/site-packages/apache_atlas/client/base_client.py", line 120, in call_api
    raise AtlasServiceException(api, response)
apache_atlas.exceptions.AtlasServiceException: Metadata service API with url http://localhost:21000/api/atlas/v2/types/typedefs/ and method HTTPMethod.POST : failed with status 409 and Response Body is :{'errorC
ode': 'ATLAS-409-00-001', 'errorMessage': 'Given type Reader already exists'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/lucas/amundsen/databuilder/databuilder/types/atlas/__init__.py", line 51, in create_or_update                                                                                                        
    self.driver.typedef.update_atlas_typedefs(AtlasTypesDef(attrs=typedef_dict))
  File "/home/lucas/amundsen/databuilder/venv/lib/python3.8/site-packages/apache_atlas/client/typedef.py", line 119, in update_atlas_typedefs
    return self.client.call_api(TypeDefClient.UPDATE_TYPE_DEFS, AtlasTypesDef, None, types_def)
  File "/home/lucas/amundsen/databuilder/venv/lib/python3.8/site-packages/apache_atlas/client/base_client.py", line 120, in call_api
    raise AtlasServiceException(api, response)
apache_atlas.exceptions.AtlasServiceException: Metadata service API with url http://localhost:21000/api/atlas/v2/types/typedefs/ and method HTTPMethod.PUT : failed with status 400 and Response Body is :{'errorC$
de': 'ATLAS-400-00-00D', 'errorMessage': 'Reader.isFollowing : attribute delete not supported'}
2021-07-06 00:43:29,011 databuilder.types.atlas INFO     Applied Reader Entity Definition
2021-07-06 00:43:29,011 databuilder.types.atlas INFO     Trying to create User Entity
2021-07-06 00:43:29,024 databuilder.types.atlas INFO     Already Exists, updating User Entity
2021-07-06 00:43:30,847 databuilder.types.atlas INFO     Applied User Entity Definition
2021-07-06 00:43:30,847 databuilder.types.atlas INFO     Trying to create Bookmark Entity
2021-07-06 00:43:54,729 databuilder.types.atlas INFO     Applied Bookmark Entity Definition
2021-07-06 00:43:54,729 databuilder.types.atlas INFO     Trying to create Report Entity
2021-07-06 00:44:18,058 databuilder.types.atlas INFO     Applied Report Entity Definition
2021-07-06 00:44:18,058 databuilder.types.atlas INFO     Trying to create Table Entity
2021-07-06 00:44:18,066 databuilder.types.atlas INFO     Already Exists, updating Table Entity
2021-07-06 00:44:39,675 databuilder.types.atlas INFO     Applied Table Entity Definition
2021-07-06 00:44:39,675 databuilder.types.atlas INFO

Assigning Table entity to all the subtypes entity definitions with postfix                                                                                                                                 [90/532]
2021-07-06 00:44:39,752 databuilder.types.atlas INFO     Assigning hive_table as a subtype of Table
2021-07-06 00:44:39,752 databuilder.types.atlas INFO     Assigning edp_table as a subtype of Table
2021-07-06 00:44:39,752 databuilder.types.atlas INFO     Assigning hbase_table as a subtype of Table
2021-07-06 00:44:39,752 databuilder.types.atlas INFO     Assigning rdbms_table as a subtype of Table
2021-07-06 00:44:41,882 databuilder.types.atlas INFO     Assignment of "Table" Entity to existing "(.*)_table$" entities Completed.

2021-07-06 00:44:41,883 databuilder.types.atlas INFO
Assigning Column entity to all the subtypes entity definitions with postfix
2021-07-06 00:44:41,944 databuilder.types.atlas INFO     Assigning rdbms_column as a subtype of Column
2021-07-06 00:44:41,944 databuilder.types.atlas INFO     Assigning hive_column as a subtype of Column
2021-07-06 00:44:41,944 databuilder.types.atlas INFO     Assigning edp_column as a subtype of Column
2021-07-06 00:44:41,944 databuilder.types.atlas INFO     Assigning hbase_column as a subtype of Column
2021-07-06 00:44:43,569 databuilder.types.atlas INFO     Assignment of "Column" Entity to existing "(.*)_column$" entities Completed.

2021-07-06 00:44:43,569 databuilder.types.atlas INFO     Trying to create User <-> Reader Entity
2021-07-06 00:44:43,575 databuilder.types.atlas INFO     Already Exists, updating User <-> Reader Entity
2021-07-06 00:44:44,020 databuilder.types.atlas INFO     Applied User <-> Reader Entity Definition
2021-07-06 00:44:44,020 databuilder.types.atlas INFO     Trying to create Reader <-> Referenceable Entity
2021-07-06 00:44:54,484 databuilder.types.atlas INFO     Applied Reader <-> Referenceable Entity Definition
2021-07-06 00:44:54,484 databuilder.types.atlas INFO     Trying to create Partition Entity
2021-07-06 00:44:54,489 databuilder.types.atlas INFO     Already Exists, updating Partition Entity
2021-07-06 00:44:54,527 databuilder.types.atlas WARNING  Error updating Partition Entity.
Traceback (most recent call last):
  File "/home/lucas/amundsen/databuilder/databuilder/types/atlas/__init__.py", line 47, in create_or_update
    self.driver.typedef.create_atlas_typedefs(AtlasTypesDef(attrs=typedef_dict))
  File "/home/lucas/amundsen/databuilder/venv/lib/python3.8/site-packages/apache_atlas/client/typedef.py", line 116, in create_atlas_typedefs
    return self.client.call_api(TypeDefClient.CREATE_TYPE_DEFS, AtlasTypesDef, None, types_def)
  File "/home/lucas/amundsen/databuilder/venv/lib/python3.8/site-packages/apache_atlas/client/base_client.py", line 120, in call_api
    raise AtlasServiceException(api, response)
apache_atlas.exceptions.AtlasServiceException: Metadata service API with url http://localhost:21000/api/atlas/v2/types/typedefs/ and method HTTPMethod.POST : failed with status 409 and Response Body is :{'errorC
ode': 'ATLAS-409-00-001', 'errorMessage': 'Given type TablePartition already exists'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucas/amundsen/databuilder/databuilder/types/atlas/__init__.py", line 51, in create_or_update
    self.driver.typedef.update_atlas_typedefs(AtlasTypesDef(attrs=typedef_dict))
  File "/home/lucas/amundsen/databuilder/venv/lib/python3.8/site-packages/apache_atlas/client/typedef.py", line 119, in update_atlas_typedefs
    return self.client.call_api(TypeDefClient.UPDATE_TYPE_DEFS, AtlasTypesDef, None, types_def)
  File "/home/lucas/amundsen/databuilder/venv/lib/python3.8/site-packages/apache_atlas/client/base_client.py", line 120, in call_api
    raise AtlasServiceException(api, response)
apache_atlas.exceptions.AtlasServiceException: Metadata service API with url http://localhost:21000/api/atlas/v2/types/typedefs/ and method HTTPMethod.PUT : failed with status 404 and Response Body is :{'errorCo
de': 'ATLAS-404-00-001', 'errorMessage': 'Given typename Table__TablePartition was invalid'}
2021-07-06 00:44:54,527 databuilder.types.atlas INFO     Applied Partition Entity Definition
2021-07-06 00:44:54,527 databuilder.types.atlas INFO     Trying to create Hive Table Partition Entity
2021-07-06 00:44:54,532 databuilder.types.atlas INFO     Already Exists, updating Hive Table Partition Entity
2021-07-06 00:44:56,281 databuilder.types.atlas INFO     Applied Hive Table Partition Entity Definition
2021-07-06 00:44:56,281 databuilder.types.atlas INFO     Trying to create Data Owner Relation Entity
2021-07-06 00:45:07,306 databuilder.types.atlas INFO     Applied Data Owner Relation Entity Definition
2021-07-06 00:45:07,306 databuilder.types.atlas INFO     Trying to create Dashboard Group Entity
2021-07-06 00:45:29,631 databuilder.types.atlas INFO     Applied Dashboard Group Entity Definition
2021-07-06 00:45:29,631 databuilder.types.atlas INFO     Trying to create Dashboard Entity
2021-07-06 00:45:51,840 databuilder.types.atlas INFO     Applied Dashboard Entity Definition
2021-07-06 00:45:51,841 databuilder.types.atlas INFO     Trying to create Dashboard Query Entity
2021-07-06 00:46:14,063 databuilder.types.atlas INFO     Applied Dashboard Query Entity Definition
2021-07-06 00:46:14,063 databuilder.types.atlas INFO     Trying to create Dashboard Chart Entity
2021-07-06 00:46:35,933 databuilder.types.atlas INFO     Applied Dashboard Chart Entity Definition
2021-07-06 00:46:35,933 databuilder.types.atlas INFO     Trying to create Dashboard Execution Entity
2021-07-06 00:46:58,912 databuilder.types.atlas INFO     Applied Dashboard Execution Entity Definition
```

## Context
We are currently using Atlas with Amundsen already, and being able to update the entity types to support newer version of Amundsen is really important. Otherwise, we would need to re-initialise Atlas with all our metadata...

## Your Environment

* Amundsen version used: `cb9fcdc339a994c7e427f80cc20903198e974d72` (git)
* Apache atlas version used: `72389767ab1094e96e07f284be3bb0f3199e3e2a` (git)

**Comment by verdan** [comment]
@mgorsk1 FYI

**Comment by mgorsk1** [comment]
Thanks for filing this @lmk-coles I will look into it and get back to you if that's ok.

**Comment by mgorsk1** [comment]
It seems that isFollowing attribute was removed last year and it was a breaking change (you can expect breaking changes between major versions and since you are on 0.13 and latest amundsen-atlas-types was 1.2 those breaking changes are expected).

Having said that, I think you have at least two not so painful options:
1.  backup and remove all Reader entities from Atlas, remove Reader typedef and subsequently run initializer again and index Reader backuped-up reader entitites
2. bring `isFollowing` attribute back in Reader entity locally and run Initializer

Apart from Reader ant TablePartition typedefs/relationdefs from the logs I see that all other definitions were loaded succesfully, am I right?

**Comment by lmk-coles** [comment]
Hi @mgorsk1 thanks for getting back to me on this issue. I will do some more testing, but for the mean time I think this issue can be closed.

A further question: Would you know if Atlas would support more flexible entity definition editing in future? It seems quite painful to update entity definitions in future (we are also using custom `_column` and `_table` types for our metadata).
