### ISSUE TITLE
Bug Report: sample_neptune_data_cleanup_job.py gives Exception: Staleness percentage of Table

### ISSUE THREAD

**Issue by iamtodor** [amundsen-io/amundsen#1319]
## Expected Behavior

I want to clean up my Neptune instance. The script outcome is to make the Neptune instance fully cleared.

## Current Behavior

It gives us Exception
```
INFO:root:Launching a job
Traceback (most recent call last):
  File "example/scripts/sample_neptune_data_cleanup_job.py", line 56, in <module>
    job.launch()
  File "/Users/itodorenko/amundsen/env/lib/python3.8/site-packages/databuilder/job/job.py", line 76, in launch
    raise e
  File "/Users/itodorenko/amundsen/env/lib/python3.8/site-packages/databuilder/job/job.py", line 66, in launch
    self.task.run()
  File "/Users/itodorenko/amundsen/env/lib/python3.8/site-packages/databuilder/task/neptune_staleness_removal_task.py", line 89, in run
    self.validate()
  File "/Users/itodorenko/amundsen/env/lib/python3.8/site-packages/databuilder/task/neptune_staleness_removal_task.py", line 100, in validate
    self._validate_node_staleness_pct()
  File "/Users/itodorenko/amundsen/env/lib/python3.8/site-packages/databuilder/task/neptune_staleness_removal_task.py", line 166, in _validate_node_staleness_pct
    self._validate_staleness_pct(
  File "/Users/itodorenko/amundsen/env/lib/python3.8/site-packages/databuilder/task/neptune_staleness_removal_task.py", line 146, in _validate_staleness_pct
    raise Exception('Staleness percentage of {} is {} %. Stopping due to over threshold {} %'
Exception: Staleness percentage of Table is 66.66666666666667 %. Stopping due to over threshold 5 %
```

## Steps to Reproduce

1. Load data to Neptune instance via [sample_data_loader_neptune](https://github.com/amundsen-io/amundsen/blob/main/databuilder/example/scripts/sample_data_loader_neptune.py)
2. Run [sample_neptune_data_cleanup_job](https://github.com/amundsen-io/amundsen/blob/main/databuilder/example/scripts/sample_neptune_data_cleanup_job.py)
3. Observe the issue

## Your Environment

```
amundsen-common==0.13.0
amundsen-databuilder==4.5.0
amundsen-gremlin==0.0.9
amundsen-rds==0.0.5
boto3==1.10.1
botocore==1.13.50
```

**Comment by feng-tao** [comment]
I assume this issue could be closed now as the pr is merged.

**Comment by iamtodor** [comment]
@feng-tao no, the bug exists despite on PR. PR changes just the way to connect to Neptune. But the logic is broken. Please, open this issue back

**Comment by iamtodor** [comment]
bug is up to date

**Comment by iamtodor** [comment]
bug is up to date
