### ISSUE TITLE
ModuleNotFoundError: No module named 'MySQLdb' with PrestoViewMetadataExtractor

### ISSUE THREAD

**Issue by tooptoop4** [amundsen-io/amundsen#1344]
```
import os
from collections import defaultdict

from pyhocon import ConfigFactory
from databuilder.extractor.base_extractor import Extractor
from databuilder.models.table_lineage import TableLineage
from databuilder.extractor.presto_view_metadata_extractor import PrestoViewMetadataExtractor
from databuilder.extractor.sql_alchemy_extractor import SQLAlchemyExtractor
from databuilder.models.table_metadata import ColumnMetadata, TableMetadata
from databuilder.loader.file_system_neo4j_csv_loader import FsNeo4jCSVLoader
from databuilder.job.job import DefaultJob
from databuilder.task.task import DefaultTask
from databuilder.publisher.neo4j_csv_publisher import Neo4jCsvPublisher

tmp_folder = '/var/tmp/amundsen/table_metadata'
node_files_folder = f'{tmp_folder}/nodes/'
relationship_files_folder = f'{tmp_folder}/relationships/'
#where_clause = f"AND t.TBL_NAME in ('') ;"
#d.NAME
where_clause = f"AND d.NAME in ('xxx')"

config = ConfigFactory.from_dict({
    f'extractor.presto_view_metadata.extractor.sqlalchemy.{SQLAlchemyExtractor.CONN_STRING}': 'mysql://user:pass@host:3306/metastore',
        f'extractor.presto_view_metadata.extractor.sqlalchemy.{PrestoViewMetadataExtractor.WHERE_CLAUSE_SUFFIX_KEY}': where_clause,
    f'loader.filesystem_csv_neo4j.{FsNeo4jCSVLoader.NODE_DIR_PATH}': node_files_folder,
    f'loader.filesystem_csv_neo4j.{FsNeo4jCSVLoader.RELATION_DIR_PATH}': relationship_files_folder,
})
job = DefaultJob(conf=config,
                 task=DefaultTask(extractor=PrestoViewMetadataExtractor(), loader=FsNeo4jCSVLoader()),
                 publisher=Neo4jCsvPublisher())
job.launch()
```

error:
```
Traceback (most recent call last):
  File "rp.py", line 31, in <module>
    job.launch()
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-5.2.2-py3.7.egg/databuilder/job/job.py", line 76, in launch
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-5.2.2-py3.7.egg/databuilder/job/job.py", line 64, in launch
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-5.2.2-py3.7.egg/databuilder/job/job.py", line 51, in _init
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-5.2.2-py3.7.egg/databuilder/task/task.py", line 45, in init
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-5.2.2-py3.7.egg/databuilder/extractor/presto_view_metadata_extractor.py", line 57, in init
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-5.2.2-py3.7.egg/databuilder/extractor/sql_alchemy_extractor.py", line 102, in from_surrounding_config
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-5.2.2-py3.7.egg/databuilder/extractor/sql_alchemy_extractor.py", line 31, in init
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-5.2.2-py3.7.egg/databuilder/extractor/sql_alchemy_extractor.py", line 56, in _get_connection
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'

```

**Comment by tooptoop4** [comment]
so i change to below, but when i run it get 0 output at all, nothing new got loaded in the UI either
```
import os
import logging
from collections import defaultdict

from pyhocon import ConfigFactory
from databuilder.extractor.base_extractor import Extractor
from databuilder.models.table_lineage import TableLineage
from databuilder.extractor.presto_view_metadata_extractor import PrestoViewMetadataExtractor
from databuilder.extractor.sql_alchemy_extractor import SQLAlchemyExtractor
from databuilder.models.table_metadata import ColumnMetadata, TableMetadata
from databuilder.loader.file_system_neo4j_csv_loader import FsNeo4jCSVLoader
from databuilder.job.job import DefaultJob
from databuilder.task.task import DefaultTask
from databuilder.publisher import neo4j_csv_publisher
from databuilder.publisher.neo4j_csv_publisher import Neo4jCsvPublisher
LOGGER = logging.getLogger(__name__)

neo4j_endpoint =f'bolt://somehost:7687'
neo4j_user = 'neo4j'
neo4j_password = 'test'
tmp_folder = '/var/tmp/amundsen/table_metadata'
node_files_folder = f'{tmp_folder}/nodes/'
relationship_files_folder = f'{tmp_folder}/relationships/'
where_clause = ''

config = ConfigFactory.from_dict({
    f'extractor.presto_view_metadata.extractor.sqlalchemy.{SQLAlchemyExtractor.CONN_STRING}': 'mysql+pymysql://u:p@somehost:3306/metastore',
        f'extractor.presto_view_metadata.extractor.sqlalchemy.{PrestoViewMetadataExtractor.WHERE_CLAUSE_SUFFIX_KEY}': where_clause,
    f'publisher.neo4j.{neo4j_csv_publisher.NEO4J_END_POINT_KEY}': neo4j_endpoint,
        f'publisher.neo4j.{neo4j_csv_publisher.NEO4J_USER}': neo4j_user,
        f'publisher.neo4j.{neo4j_csv_publisher.NEO4J_PASSWORD}': neo4j_password,
f'publisher.neo4j.{neo4j_csv_publisher.JOB_PUBLISH_TAG}': 'cli',
'task.progress_report_frequency': 0.1,
f'loader.filesystem_csv_neo4j.{FsNeo4jCSVLoader.NODE_DIR_PATH}': node_files_folder,
    f'loader.filesystem_csv_neo4j.{FsNeo4jCSVLoader.RELATION_DIR_PATH}': relationship_files_folder,
})
job = DefaultJob(conf=config,
                 task=DefaultTask(extractor=PrestoViewMetadataExtractor(), loader=FsNeo4jCSVLoader()),
                 publisher=Neo4jCsvPublisher())
job.launch()

```

**Comment by tooptoop4** [comment]
'publisher.neo4j.{}'.format(neo4j_csv_publisher.NODE_FILES_DIR): node_files_folder,
    'publisher.neo4j.{}'.format(neo4j_csv_publisher.RELATION_FILES_DIR): relationship_files_folder,

adding that solved it
