### ISSUE TITLE
SQLite3 OperationalError when using `amundsen-frontend-oidc:3.11.1`

### ISSUE THREAD

**Issue by jacobnosal** [amundsen-io/amundsen#1387]
I am deploying Amundsen on Kubernetes with OIDC enabled using the helm chart. The frontend service throws an error when attempting to load `gunicorn` workers because it cannot open the database at `sqlite:///sessions.db` which does not exist. The deployment documentation does not say whether I need to create this database and, if so, what schema should be used, etc.

## Expected Behavior
Documentation states the deployment instructions for handling the sessions database for Flask usage in amanner where multiple workers and frontend replicas can share sessions information. 

## Current Behavior
Documentation does not state the required configurations and the helm chart and throws an `OperationalError`.
```python
[2021-07-26 14:38:46 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-07-26 14:38:46 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2021-07-26 14:38:46 +0000] [1] [INFO] Using worker: sync
[2021-07-26 14:38:46 +0000] [8] [INFO] Booting worker with pid: 8
[2021-07-26 14:38:46 +0000] [9] [INFO] Booting worker with pid: 9
[2021-07-26 14:38:46 +0000] [10] [INFO] Booting worker with pid: 10
[2021-07-26 14:38:46 +0000] [11] [INFO] Booting worker with pid: 11
Registering post_exec action_log entry_point: logging_action_log = amundsen_application.log.action_log_callback:logging_action_log
Using requested Flask module flaskoidc and class FlaskOIDC
[2021-07-26 14:38:49 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/amundsen_application/wsgi.py", line 11, in <module>
    application = create_app()
  File "/app/amundsen_application/__init__.py", line 53, in create_app
    app = app_wrapper_class(__name__, static_folder=static_dir, template_folder=tmpl_dir, **args)
  File "/usr/local/lib/python3.7/site-packages/flaskoidc/__init__.py", line 78, in __init__
    self.db.create_all()
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4664, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2094, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2086, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2021-07-26 14:38:49 +0000] [8] [INFO] Worker exiting (pid: 8)
```

## Possible Solution
[This line](https://github.com/amundsen-io/amundsen/blob/c4e3296c1059d4b2b97d0d40eabc157428c3835a/amundsen-kube-helm/templates/helm/templates/deployment-frontend.yaml#L72) could be changed to allow for configuration or instructions could be added on which schema needs to be used to create tables, databases, etc.

The solution should address how to run the frontend service with oidc and more than 1 replica and sessions to be shared between multiple workers/pods of the frontend service.

## Steps to Reproduce

1. Modify `values.yaml` parameter as follows: 
```yaml
frontEnd:
  image: amundsendev/amundsen-frontend-oidc
  imageTag: 3.11.1
  oidcEnabled: true
```
2. Deploy using Helm to a kubernetes cluster.

## Context
I am attempting to enable OIDC for enterprise authentication and am unable to get the frontend service running.

## Your Environment
* Amundsen version used: Frontend Service 3.11.1
* Deployment (k8s or native): Kubernetes
  ```bash
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", 
  GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", 
  GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", 
  GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", 
  GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  ```

**Comment by jacobnosal** [comment]
This turned out to be a problem as the cluster I am running on has a policy disallowing root users. I modified the dockerfiles for frontend and metadata to change the permissions of the `/app` directory and parameterized the `securityContext.runAsUser` on each of the `{metadata,frontend,search}-deployment.yaml` files.
