### ISSUE TITLE
Using MySQL as proxy but keeps telling me Access denied Bug Report

### ISSUE THREAD

**Issue by shiyishiaa** [amundsen-io/amundsen#1393]
I'm trying to use mysql as proxy but every metadata api run failed though username and password has been changed in `metadata_service/config.py`.
I run test examples in `tests/unit/proxy/test_mysql_proxy.py` and got all success.

## Expected Behavior
Show some true behavior.

## Current Behavior
```
Traceback (most recent call last):
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/flask/views.py", line 87, in view
    self = view.view_class(*class_args, **class_kwargs)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/metadata_service/api/table.py", line 29, in __init__
    self.client = get_proxy_client()
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/metadata_service/proxy/__init__.py", line 41, in get_proxy_client
    _proxy_client = client(host=host,
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/metadata_service/proxy/mysql_proxy.py", line 120, in __init__
    is_the_latest_schema = self.client.validate_schema_version()
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/metadata_service/client/rds_client.py", line 73, in validate_schema_version
    with self.engine.begin() as conn:
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2147, in begin
    conn = self._contextual_connect(close_with_result=close_with_result)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/root/amundsen/metadata/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1045, "Access denied for user 'user'@'localhost' (using password: YES)")
```

## Possible Solution
Don't konw

## Steps to Reproduce

1.Modify username and password etc. in config.py
```
    PROXY_HOST = '127.0.0.1'   # type: ignore
    PROXY_PORT = '3306'   # type: ignore
    PROXY_USER = 'root'   # type: ignore
    PROXY_PASSWORD = '123456'   # type: ignore
    SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI', 'mysql://root:123456@127.0.0.1:3306/test')
```

2.Run `python3 metadata_service/metadata_wsgi.py`
3.Open 'http://192.168.1.115:5000'. (where the server lies)

## Context
Server runs on ubuntu 20.04, ip 192.168.1.115
Within LAN, open http://192.168.1.115:5000 using Windows 10 Edge

## Your Environment
* Amunsen version used: `main` branch
* Data warehouse stores: MySQL
* Deployment (k8s or native): local

**Comment by shiyishiaa** [comment]
I tried [https://github.com/amundsen-io/amundsen/releases/tag/frontend-3.12.0](3.12.0) but found it still of no use. :(

**Comment by feng-tao** [comment]
cc @xuan616

**Comment by xuan616** [comment]
Hi @shiyishiaa, may I know if you have initialized the database

**Comment by shiyishiaa** [comment]
> Hi @shiyishiaa, may I know if you have initialized the database

Sorry for late reply. Yes, I did. After mysql, I tried Neo4j and everything works fine for me.

**Comment by xuan616** [comment]
I am not sure if I understand the issue correctly. Sounds like the same connection string('SQLALCHEMY_DATABASE_URI') worked for the command `flask rds initdb` but not api endpoints in metadata service?

**Comment by shiyishiaa** [comment]
> I am not sure if I understand the issue correctly. Sounds like the same connection string('SQLALCHEMY_DATABASE_URI') worked for the command `flask rds initdb` but not api endpoints in metadata service?

Yes, you're right.

**Comment by xuan616** [comment]
The error occurred when the service was trying to verify the schema version and it failed due to the rejected connection. Could it be an issue caused by the remote access or some loss of privileges on user?

**Comment by shiyishiaa** [comment]
> The error occurred when the service was trying to verify the schema version and it failed due to the rejected connection. Could it be an issue caused by the remote access or some loss of privileges on user?

I don't think so. I successfully logged in via the database tool of IDEA with root account. And everything worked well.

**Comment by xuan616** [comment]
I was not able to reproduce this issue on my end. Could you provide more details, like how each component was deployed at your side. Or you can slack me in Amundsen slack if you are going to share some screenshots. Thx.

**Comment by shiyishiaa** [comment]
> I was not able to reproduce this issue on my end. Could you provide more details, like how each component was deployed at your side. Or you can slack me in Amundsen slack if you are going to share some screenshots. Thx.

OK, I will try it later. Thanks for your patience! :)
Let close this issue temporarily.

**Comment by feng-tao** [comment]
thanks @xuan616 for the debugging
