### ISSUE TITLE
Cannot search in frontend

### ISSUE THREAD

**Issue by mschuch** [amundsen-io/amundsen#1437]
## Expected Behavior
amundsensearchservice  API to Elasticsearch is working and i can search for results in the frontend.

## Current Behavior
```
2021-08-11T14:23:55+0000.940 [INFO] base.log_request_success:194 (1:Thread-4) - GET http://elasticsearch:9200/table_search_index/_search [status:200 request:0.008s]
2021-08-11T14:23:55+0000.941 [ERROR] app.log_exception:1761 (1:Thread-4) - Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flasgger/utils.py", line 273, in wrapper
    return function(*args, **kwargs)
  File "/app/search_service/api/table.py", line 51, in get
    return SearchTableResultSchema().dump(results), HTTPStatus.OK
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 556, in dump
    result = self._serialize(processed_obj, many=many)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 520, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/fields.py", line 311, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/fields.py", line 894, in _serialize
    ret = self._format_num(value)  # type: _T
  File "/usr/local/lib/python3.7/site-packages/marshmallow/fields.py", line 869, in _format_num
    return self.num_type(value)
**TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'**
2021-08-11T14:23:55+0000.943 [INFO] _internal._log:225 (1:Thread-4) - 10.1.0.181 - - [11/Aug/2021 14:23:55] "GET /search?query_term=test&page_index=0 HTTP/1.1" 500 -
```
## Steps to Reproduce

1. Install the latest docker example
2. Insert sample Data from Quick Tutorial
3. Search for anything in the frontend
4.

## Your Environment

* Amunsen version used:  build from Dockerfile and used latest images from docker hub, did not change anything
* Deployment (k8s or native): K8S

**Comment by mschuch** [comment]
Hi all,
for everyone that stumbles over the same problem. This happens when you mix the Docker Containers. In my case, Kubernetes pulled the images from Docker Hub instead of my local repository. This gave me a real headache, but maybe someone finds that helpful in the future.
