### ISSUE TITLE
OIDC authentication - session not persists issue

### ISSUE THREAD

**Issue by woodchuck1206** [amundsen-io/amundsen#1441]
I'm trying to implement Google OIDC authentication on an existing amundsen.
All the micro services (search, metadata, frontend) are deployed with helm on AWS EKS and, without authentication, it works.
But when I enable OIDC, as you'll see below, session information does not persist and frontend starts showing a "Something went wrong..." message.

Here's the related logs from frontend. (sensitive info replaced with arbitrary number of *'s + I put the 'test_data' in session for debugging purposes)
```
2021-08-13T17:23:20+09:00 /usr/local/lib/python3.7/site-packages/flask/json/__init__.py:179: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
2021-08-13T17:23:20+09:00   rv = _json.dumps(obj, **kwargs)
2021-08-13T17:23:20+09:00 /usr/local/lib/python3.7/site-packages/flask/json/__init__.py:205: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
2021-08-13T17:23:20+09:00   return _json.loads(s, **kwargs)
2021-08-13T17:23:20+09:00 2021-08-13T08:23:20+0000.168 [DEBUG] __init__._before_request:23 (11:MainThread) - Whitelisted Endpoint: status,healthcheck,health,logout
2021-08-13T17:23:20+09:00 2021-08-13T08:23:20+0000.169 [ERROR] models._fetch_token:88 (11:MainThread) - Calling _fetch_token(name=google)...
2021-08-13T17:23:20+09:00 2021-08-13T08:23:20+0000.169 [ERROR] models._fetch_token:92 (11:MainThread) - <SecureCookieSession {'test_data': 'test data', 'user': {'__id': '*****@*************.com', 'at_hash': '**************', 'aud': '***********************', 'azp': '*****************', 'display_name': '******************', 'email': '*****************', 'email_verified': True, 'exp': 1628846069, 'family_name': '******', 'given_name': '***********', 'hd': '***************, 'iat': 1628842469, 'iss': 'https://accounts.google.com', 'locale': 'en', 'name': '************', 'nonce': '*************', 'picture': '****************', 'profile_url': '', 'sub': '**********', 'user_id': '*****************'}}>
2021-08-13T17:23:32+09:00 /usr/local/lib/python3.7/site-packages/flask/json/__init__.py:179: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
2021-08-13T17:23:32+09:00   rv = _json.dumps(obj, **kwargs)
2021-08-13T17:23:32+09:00 /usr/local/lib/python3.7/site-packages/flask/json/__init__.py:179: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
2021-08-13T17:23:32+09:00   rv = _json.dumps(obj, **kwargs)
2021-08-13T17:23:32+09:00 /usr/local/lib/python3.7/site-packages/flask/json/__init__.py:179: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
2021-08-13T17:23:32+09:00   rv = _json.dumps(obj, **kwargs)
2021-08-13T17:23:32+09:00 2021-08-13T08:23:32+0000.720 [DEBUG] __init__._before_request:23 (10:MainThread) - Whitelisted Endpoint: status,healthcheck,health,logout
2021-08-13T17:23:32+09:00 2021-08-13T08:23:32+0000.720 [ERROR] models._fetch_token:88 (10:MainThread) - Calling _fetch_token(name=google)...
2021-08-13T17:23:32+09:00 2021-08-13T08:23:32+0000.720 [ERROR] models._fetch_token:92 (10:MainThread) - <SecureCookieSession {'test_data': 'test data'}>
2021-08-13T17:23:32+09:00 2021-08-13T08:23:32+0000.721 [ERROR] models._fetch_token:100 (10:MainThread) - 'user'
2021-08-13T17:23:32+09:00 2021-08-13T08:23:32+0000.721 [ERROR] __init__._before_request:59 (10:MainThread) - User not logged in, redirecting to auth
2021-08-13T17:23:32+09:00 Traceback (most recent call last):
2021-08-13T17:23:32+09:00   File "/usr/local/lib/python3.7/site-packages/flaskoidc/models.py", line 94, in _fetch_token
2021-08-13T17:23:32+09:00     user_id=session["user"]["__id"],
2021-08-13T17:23:32+09:00   File "/usr/local/lib/python3.7/site-packages/flask/sessions.py", line 83, in __getitem__
2021-08-13T17:23:32+09:00     return super(SecureCookieSession, self).__getitem__(key)
2021-08-13T17:23:32+09:00 KeyError: 'user'
```

My suspicions are:
1. Google OIDC has different specs, for example, in my setup, OAuth2Token (flaskoidc) saves access token, refresh token and such, instead of name or user_id. So I tweaked the flaskoidc lib to authenticate the current session user using some google apis, but still the error persists.
2. Metadata also produces suspicious logs. Except the healthcheck signals, it always returns 302. Is it meant to work like this? I'm not sure. 

## Expected Behavior
meant to work out of the box?

## Current Behavior
frontend shows 'something went wrong' messages after login when hooked with google oidc

## Possible Solution
-

## Steps to Reproduce
1. deploy amundsen using the helm chart in gith repo using frontend-oidc: 3.11.1, metadata-oidc: 3.5.0, search:2.5.1 with flask OIDC env variables for Google oidc

**Comment by shlsheth263** [comment]
Any update on this issue?

i am facing the same issue

**Comment by woodchuck1206** [comment]
@shlsheth263 I solved this issue by disabling Amundsen authentication and building a custom authentication layer in front of it & modifying Amundsen source to use it. Seems like many users heavily modify Amundsen due to issues like this one.

**Comment by drodrigues3** [comment]
@shlsheth263 could you please share how you fix this issue?

**Comment by shlsheth263** [comment]
@drodrigues3 https://www.stemma.ai/blog/how-to-setup-oidc-authentication-in-amundsen

Ive followed this.

**Comment by miguelpromptly** [comment]
I'm facing the exact same issue. I've tried solving that guide above, but did not solve it for me. @shlsheth263 anything in the guide you reckon was the key change or any other advice?

**Comment by drodrigues3** [comment]
@miguelpromptly  for me worked after I did downgrade of the flaskoidc lib, now I'm using flaskoidc==0.2.3 and this is working well

**Comment by shlsheth263** [comment]
@drodrigues3 were you able to retrieve user details from google oidc ?

i am getting following error:

ERROR:metadata_service.config:404 Client Error: Not Found for url: https://accounts.google.com/api/v1/users?q=<email_id>&limit=1
amundsenmetadata    | Traceback (most recent call last):
amundsenmetadata    |   File "/app/metadata_service/config.py", line 98, in get_user_details
amundsenmetadata    |     user_info = get_user_from_oidc(user_id=user_id)
amundsenmetadata    |   File "/app/metadata_service/config.py", line 54, in get_user_from_oidc
amundsenmetadata    |     response.raise_for_status()
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
amundsenmetadata    |     raise HTTPError(http_error_msg, response=self)
amundsenmetadata    | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://accounts.google.com/api/v1/users?q=<email_id>&limit=1

**Comment by edsonlalmeida** [comment]
I'm having this same problem but with okta, someone managed to solve it?

**Comment by jgc93** [comment]
> @shlsheth263 I solved this issue by disabling Amundsen authentication and building a custom authentication layer in front of it & modifying Amundsen source to use it. Seems like many users heavily modify Amundsen due to issues like this one.

Hey @shlsheth263 , how did you overcome this? I would love any insight. facing exact same issue.

**Comment by Jrecos** [comment]
Any update in this issue, guys? I'm facing the exact same issue.

**Comment by pedronaresi** [comment]
Any update?

**Comment by NiravLangaliya** [comment]
I am getting similar issue so adding @verdan , if he can help here.

**Comment by pedronaresi** [comment]
up

**Comment by NiravLangaliya** [comment]
@verdan, I have notice that if I am running locally ( as http://localhost:5002 )  and integrating Okta then I am not getting session issue but if I integrate localhost and put ALB on top of and have ALB url register into Okta then session is getting lost.

**Comment by pedronaresi** [comment]
Same conditions here @NiravLangaliya

**Comment by pedronaresi** [comment]
@verdan

**Comment by pedronaresi** [comment]
anyone?

**Comment by MehdiSfr** [comment]
i am getting the same but things are working! I use 
flaskoids==1.0.4 
on all services and i install that explicitly not through 
pip3 install -e .[oidc]
