### ISSUE TITLE
Bug Report - Deploying sample_data_loader has error

### ISSUE THREAD

**Issue by uploadWizdom** [amundsen-io/amundsen#1474]
I'm trying to deploy sample_data_loader in Amundsen environment that runs in docker from a CENTOS8 machine.
I've tried multiple versions of python:
$ python3.6 --version
Python 3.6.8
$ python3.7 --version
Python 3.7.9
$ python3.8 --version
Python 3.8.7

Same error
Traceback (most recent call last):
  File "example/scripts/sample_data_loader.py", line 374, in <module>
    'databuilder.models.application.Application')
  File "example/scripts/sample_data_loader.py", line 105, in run_csv_job
    publisher=Neo4jCsvPublisher()).launch()
  File "/opt/sandbox/gitLocal/vEnvs/amundsenVenv/lib64/python3.6/site-packages/amundsen_databuilder-6.0.2-py3.6.egg/databuilder/job/job.py", line 76, in launch
  File "/opt/sandbox/gitLocal/vEnvs/amundsenVenv/lib64/python3.6/site-packages/amundsen_databuilder-6.0.2-py3.6.egg/databuilder/job/job.py", line 64, in launch
  File "/opt/sandbox/gitLocal/vEnvs/amundsenVenv/lib64/python3.6/site-packages/amundsen_databuilder-6.0.2-py3.6.egg/databuilder/job/job.py", line 51, in _init
  File "/opt/sandbox/gitLocal/vEnvs/amundsenVenv/lib64/python3.6/site-packages/amundsen_databuilder-6.0.2-py3.6.egg/databuilder/task/task.py", line 45, in init
  File "/opt/sandbox/gitLocal/vEnvs/amundsenVenv/lib64/python3.6/site-packages/amundsen_databuilder-6.0.2-py3.6.egg/databuilder/extractor/csv_extractor.py", line 47, in init
  File "/opt/sandbox/gitLocal/vEnvs/amundsenVenv/lib64/python3.6/site-packages/amundsen_databuilder-6.0.2-py3.6.egg/databuilder/extractor/csv_extractor.py", line 59, in _load_csv
  File "/opt/sandbox/gitLocal/vEnvs/amundsenVenv/lib64/python3.6/site-packages/amundsen_databuilder-6.0.2-py3.6.egg/databuilder/extractor/csv_extractor.py", line 59, in <listcomp>
TypeError: __init__() got an unexpected keyword argument 'exec_date'

I've updated the connection details in the script.

## Expected Behavior
Data should be populated in Amundsen

## Current Behavior
Error

## Steps to Reproduce
 $ python3 -m venv venv
 $ source venv/bin/activate
 $ pip3 install --upgrade pip
 $ pip3 install -r requirements.txt
 $ python3 setup.py install
 $ python3 example/scripts/sample_data_loader.py

## Your Environment

* Amunsen version used: latest
* Data warehouse stores: postgresql
* Deployment (k8s or native): docker

**Comment by uploadWizdom** [comment]
Solution from https://github.com/amundsen-io/amundsen/issues/1442#issuecomment-902994567
