### ISSUE TITLE
Error with login OIDC

### ISSUE THREAD

**Issue by PratikKhandelwal17** [amundsen-io/amundsen#1525]
```
amundsenfrontend    | ERROR:root:Encountered exception: 'NoneType' object has no attribute 'get'
amundsenfrontend    | Traceback (most recent call last):
amundsenfrontend    |   File "/app/amundsen_application/api/v0.py", line 26, in current_user
amundsenfrontend    |     user = app.config['AUTH_USER_METHOD'](app)
amundsenfrontend    |   File "/app/amundsen_application/oidc_config.py", line 35, in get_auth_user
amundsenfrontend    |     user_info = load_user(session.get("user"))
amundsenfrontend    |   File "/app/amundsen_application/models/user.py", line 24, in load_user
amundsenfrontend    |     if _str_no_value(user_data.get('user_id')):
amundsenfrontend    | AttributeError: 'NoneType' object has no attribute 'get'

```

getting this error while trying to use OIDC for login, i'm a junior developer having less experience, please help

**Comment by jruanob** [comment]
@PratikKhandelwal17 did you solve this issue? Im having the same problem.
