### ISSUE TITLE
Bug Report: Bigquery preview feature doesn't work when numeric type is present in the table

### ISSUE THREAD

**Issue by bsilva89** [amundsen-io/amundsen#1658]
## Expected Behavior
The Bigquery preview feature should work with the most importante data types available for Bigquery tables.

## Current Behavior
Working with date, boolean, integer, string and float data types but not with numeric/decimal.

## Possible Solution
Consider the numeric type when serializing the json before the response. I'll be opening a PR in order to fix this issue. (PR #1660)

## Steps to Reproduce

1. enable bigquery preview in the docker-amundsen-local.yml, or whatever compose file you are using, adding in the environment variables section the below. I'm using the provided example script just for simplicity of this demo. (and don't forget to change the GCP project).
```
PREVIEW_CLIENT_ENABLED=true
PREVIEW_CLIENT=amundsen_application.base.examples.example_bigquery_preview_client.BigqueryPreviewClient 
```
2. build amundsen images with bigquery_preview option for frontend
3. start using docker-compose
4. ingest some BQ metadata tables with and without NUMERIC data type columns.
5. the error should appear in the tables with numeric types. Other tables should work just fine.

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/42705595/149243033-ad938c4d-eb7c-4012-b27f-082470bd3735.png)

## Error log

```
[ERROR] v0.get_table_preview:67 (1:Thread-73) - Encountered exception: Object of type Decimal is not JSON serializable
--
Traceback (most recent call last):
File "/app/amundsen_application/api/preview/v0.py", line 47, in get_table_preview
response = PREVIEW_CLIENT_INSTANCE.get_preview_data(params=request.get_json())
File "/app/amundsen_application/base/base_bigquery_preview_client.py", line 68, in get_preview_data
payload = jsonify({"preview_data": data})
File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 321, in jsonify
dumps(data, indent=indent, separators=separators) + '\n',
File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 179, in dumps
rv = _json.dumps(obj, **kwargs)
File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
**kw).encode(obj)
File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 81, in default
return _json.JSONEncoder.default(self, o)
File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
[INFO] _internal._log:225 (1:Thread-73) - 172.18.0.1 - - [12/Jan/2022 23:02:33] "POST /api/preview/v0/ HTTP/1.1" 500 -
```

## Your Environment

* Amunsen version used: frontend-4.0.0
* Data warehouse stores: BQ
* Deployment (k8s or native): native using VM and GCP cloud.
* Link to your fork or repository: https://github.com/bsilva89/amundsen

**Comment by bsilva89** [comment]
Solved with PR #1660
