### ISSUE TITLE
Bug Report - dbt extractor sources key error

### ISSUE THREAD

**Issue by petehanssens** [amundsen-io/amundsen#1674]
## Expected Behavior
dbt data loader should be able to handle outputs with sources

## Current Behavior
Currently breaks with:
```
KeyError: 'source.dbt_airflow.xxx.xxx'
```

## Possible Solution
Handle keys that are sources better

## Steps to Reproduce

1. Databuilder on Astronomer
2. Run: dbt docs generate
3. Run the extractor

## Screenshots (if appropriate)
```[2022-01-18 05:12:30,937] {file_system_neo4j_csv_loader.py:88} INFO - Deleting directory /usr/local/airflow/include/dbt/target//relationships
[2022-01-18 05:12:30,937] {file_system_neo4j_csv_loader.py:88} INFO - Deleting directory /usr/local/airflow/include/dbt/target//nodes
[2022-01-18 05:12:30,939] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/amundsen/dbt_metadata_loader_dag.py", line 141, in dbt_metadata_loader_function
    manifest_file_loc=DBT_MANIFEST_FILE,
  File "/usr/local/airflow/dags/amundsen/dbt_metadata_loader_dag.py", line 75, in run_dbt_job
    DefaultJob(conf=job_config, task=task, publisher=Neo4jCsvPublisher()).launch()
  File "/usr/local/lib/python3.7/site-packages/databuilder/job/job.py", line 76, in launch
    raise e
  File "/usr/local/lib/python3.7/site-packages/databuilder/job/job.py", line 66, in launch
    self.task.run()
  File "/usr/local/lib/python3.7/site-packages/databuilder/task/task.py", line 75, in run
    record = self.extractor.extract()
  File "/usr/local/lib/python3.7/site-packages/databuilder/extractor/dbt_extractor.py", line 191, in extract
    return next(self._extract_iter)
  File "/usr/local/lib/python3.7/site-packages/databuilder/extractor/dbt_extractor.py", line 292, in _get_extract_iter
    table_key=dbt_id_to_table_key[upstream],
KeyError: 'source.dbt_airflow.xxx.xxx'
[2022-01-18 05:12:30,942] {taskinstance.py:1512} INFO - Marking task as FAILED. dag_id=dbt_metadata_loader_dag, task_id=dbt_metadata_loader, execution_date=20220118T050232, start_date=20220118T051004, end_date=20220118T051230
[2022-01-18 05:12:30,995] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-01-18 05:12:31,032] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check```


## Context
<!--- How has this issue affected you? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->
This breaks the dbt data loader

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Amunsen version used: latest
* Data warehouse stores: dbt (snowflake)
* Deployment (k8s or native): Astronomer
* Link to your fork or repository: not possible

**Comment by feng-tao** [comment]
@petehanssens could you take a look at https://github.com/amundsen-io/amundsen/pull/1653/files and see if it fixes your issue?
