### ISSUE TITLE
Bug Report WARNING:elasticsearch:PUT  Pls Help

### ISSUE THREAD

**Issue by pongpanot0** [amundsen-io/amundsen#1738]
WARNING:elasticsearch:PUT http://localhost:9200/table_3c2da9b3-2345-4a79-9541-c40bda1a5dd9 [status:400 request:0.274s] i got that in python3 example/scripts/sample_data_loader.py 
Traceback (most recent call last):
  File "C:\Users\66985\Desktop\docker\step1\amundsen\databuilder\example\scripts\sample_data_loader.py", line 384, in <module>
    job_es_table.launch()
  File "C:\Users\66985\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\amundsen_databuilder-6.7.1-py3.9.egg\databuilder\job\job.py", line 76, in launch
  File "C:\Users\66985\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\amundsen_databuilder-6.7.1-py3.9.egg\databuilder\job\job.py", line 72, in launch
  File "C:\Users\66985\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\amundsen_databuilder-6.7.1-py3.9.egg\databuilder\publisher\base_publisher.py", line 40, in publish
  File "C:\Users\66985\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\amundsen_databuilder-6.7.1-py3.9.egg\databuilder\publisher\base_publisher.py", line 37, in publish
  File "C:\Users\66985\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\amundsen_databuilder-6.7.1-py3.9.egg\databuilder\publisher\elasticsearch_publisher.py", line 93, in publish_impl
  File "C:\Users\66985\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\elasticsearch\client\utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "C:\Users\66985\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\elasticsearch\client\indices.py", line 90, in create
    return self.transport.perform_request('PUT', _make_path(index),
  File "C:\Users\66985\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\elasticsearch\transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "C:\Users\66985\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\elasticsearch\connection\http_urllib3.py", line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File "C:\Users\66985\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\elasticsearch\connection\base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [table : {properties={schema={analyzer=simple, type=text, fields={raw={type=keyword}}}, cluster={analyzer=simple, type=text, fields={raw={type=keyword}}}, description={analyzer=simple, type=text}, display_name={type=keyword}, column_descriptions={analyzer=simple, type=text}, programmatic_descriptions={analyzer=simple, type=text}, tags={type=keyword}, badges={type=keyword}, database={analyzer=simple, type=text, fields={raw={type=keyword}}}, total_usage={type=long}, name={analyzer=simple, type=text, fields={raw={type=keyword}}}, last_updated_timestamp={format=epoch_second, type=date}, unique_usage={type=long}, column_names={analyzer=simple, type=text, fields={raw={normalizer=column_names_normalizer, type=keyword}}}, key={type=keyword}}}]')

- [ ] 
![fail](https://user-images.githubusercontent.com/61924591/156026580-37135827-681f-47f0-bfc7-23f9eb8a42c8.png)

**Comment by ajyh** [comment]
It worked for me adding update station, thanks.
https://pypi.org/project/amundsen-common/0.26.0/
https://pypi.org/project/amundsen-databuilder/6.7.1/

**Comment by pongpanot0** [comment]
it work Thankyou
