### ISSUE TITLE
Bug Report elasticsearch exception for sample_neptune_loader

### ISSUE THREAD

**Issue by amandeep848** [amundsen-io/amundsen#1748]
## Expected Behavior
<WARNING:elasticsearch:PUT https://my aws ES endpoint/table_a54a9a96-c246-4bcd-b417-2d8c005c3290 [status:400 request:0.069s]
INFO:databuilder.callback.call_back:No callbacks to notify
Traceback (most recent call last):
  File "example/scripts/sample_data_loader_neptune.py", line 403, in <module>
    job_es_table.launch()
  File "/tmp/amundsen/venv/lib/python3.7/site-packages/databuilder/job/job.py", line 76, in launch
    raise e
  File "/tmp/amundsen/venv/lib/python3.7/site-packages/databuilder/job/job.py", line 72, in launch
    self.publisher.publish()
  File "/tmp/amundsen/venv/lib/python3.7/site-packages/databuilder/publisher/base_publisher.py", line 40, in publish
    raise e
  File "/tmp/amundsen/venv/lib/python3.7/site-packages/databuilder/publisher/base_publisher.py", line 37, in publish
    self.publish_impl()
  File "/tmp/damundsen/venv/lib/python3.7/site-packages/databuilder/publisher/elasticsearch_publisher.py", line 93, in publish_impl
    self.elasticsearch_client.indices.create(index=self.elasticsearch_new_index, body=self.elasticsearch_mapping)
  File "/tmp/amundsen/venv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/tmp/amundsen/venv/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 146, in create
    "PUT", _make_path(index), params=params, headers=headers, body=body
  File "/tmp/amundsen/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 466, in perform_request
    raise e
  File "/tmp/damundsen/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 434, in perform_request
    timeout=timeout,
  File "/tmp/amundsen/venv/lib/python3.7/site-packages/elasticsearch/connection/http_requests.py", line 216, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/tmp/amundsen/venv/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 329, in _raise_error
    status_code, error_message, additional_info

elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [schema : {analyzer=simple, type=text, fields={raw={type=keyword}}}] [cluster : {analyzer=simple, type=text, fields={raw={type=keyword}}}] [description : {analyzer=simple, type=text}] [display_name : {type=keyword}] [column_descriptions : {analyzer=simple, type=text}] [programmatic_descriptions : {analyzer=simple, type=text}] [tags : {type=keyword}] [badges : {type=keyword}] [database : {analyzer=simple, type=text, fields={raw={type=keyword}}}] [total_usage : {type=long}] [name : {analyzer=simple, type=text, fields={raw={type=keyword}}}] [last_updated_timestamp : {format=epoch_second, type=date}] [unique_usage : {type=long}] [column_names : {analyzer=simple, type=text, fields={raw={normalizer=column_names_normalizer, type=keyword}}}] [key : {type=keyword}]')->

* Amunsen version used: Databuilder: 6.7.1 Common 0.26.0 Amundsen-Gremlin 0.0.13 AWS ES : 6.8

**Comment by whrocha** [comment]
Same problem here, does you solved?

**Comment by whrocha** [comment]
@amandeep848 could you fix the problem?

**Comment by muthuramanm** [comment]
@amandeep848 could you fix the problem?

**Comment by whrocha** [comment]
Hello!

I have been fixed the problem by putting the version of amundsen-common to 0.24.1

- My `requirements.txt` file is setup as shown below:

```text
amundsen-databuilder==6.5.2
amundsen-gremlin==0.0.13
gremlinpython==3.4.10
requests-aws4auth==1.1.1
boto3==1.21.23
botocore==1.24.23
typing-extensions==4.1.1
overrides==6.1.0
amundsen-common==0.24.1
```

- My Glue databuilder script:

```python
import logging
import os
import uuid
import boto3
import textwrap
import json

from datetime import date

from elasticsearch import Elasticsearch
from pyhocon import ConfigFactory

from databuilder.clients.neptune_client import NeptuneSessionClient
from databuilder.extractor.es_last_updated_extractor import EsLastUpdatedExtractor
from databuilder.extractor.neptune_search_data_extractor import NeptuneSearchDataExtractor

from databuilder.job.job import DefaultJob
from databuilder.loader.file_system_elasticsearch_json_loader import FSElasticsearchJSONLoader
from databuilder.loader.file_system_neptune_csv_loader import FSNeptuneCSVLoader
from databuilder.publisher.elasticsearch_constants import (
    DASHBOARD_ELASTICSEARCH_INDEX_MAPPING, USER_ELASTICSEARCH_INDEX_MAPPING,
)
from databuilder.publisher.elasticsearch_publisher import ElasticsearchPublisher
from databuilder.publisher.neptune_csv_publisher import NeptuneCSVPublisher
from databuilder.task.task import DefaultTask
from databuilder.transformer.base_transformer import ChainedTransformer, NoopTransformer
from databuilder.transformer.dict_to_model import MODEL_CLASS, DictToModel
from databuilder.transformer.generic_transformer import (
    CALLBACK_FUNCTION, FIELD_NAME, GenericTransformer,
)

from databuilder.extractor.glue_extractor import GlueExtractor
from databuilder.task.neptune_staleness_removal_task import NeptuneStalenessRemovalTask


es_host = os.getenv('ES_HOST')

neptune_host = os.getenv('NEPTUNE_HOST')
neptune_port = os.getenv('NEPTUNE_PORT', 8182)
neptune_iam_role_name = os.getenv('NEPTUNE_IAM_ROLE')

S3_BUCKET_NAME = os.getenv('S3_BUCKET_NAME')
today = date.today()
S3_DATA_PATH = f'amundsen_data/glue_extractor/year={today.year}/month={today.month}/day={today.day}'

AWS_REGION = os.getenv('AWS_REGION')
GLUE_DATABASE_IDENTIFIER = os.getenv('GLUE_DATABASE_IDENTIFIER')

es = Elasticsearch(
    '{}'.format(es_host),
    scheme="https",
    port=443,
)

NEPTUNE_ENDPOINT = '{}:{}'.format(neptune_host, neptune_port)

LOGGER = logging.getLogger(__name__)


def run_glue_job(job_name):
    """Run Glue metadata extraction

    Args:
        job_name (string): job name
    """

    tmp_folder = '/var/tmp/amundsen/{job_name}'.format(job_name=job_name)
    node_files_folder = '{tmp_folder}/nodes'.format(tmp_folder=tmp_folder)
    relationship_files_folder = '{tmp_folder}/relationships'.format(tmp_folder=tmp_folder)

    loader = FSNeptuneCSVLoader()
    publisher = NeptuneCSVPublisher()

    with open("databases.json") as jsonFile:

        filters = json.load(jsonFile)

    job_config = ConfigFactory.from_dict({
        f'extractor.glue.{GlueExtractor.CLUSTER_KEY}': GLUE_DATABASE_IDENTIFIER,
        f'extractor.glue.{GlueExtractor.FILTER_KEY}': filters,
        loader.get_scope(): {
            FSNeptuneCSVLoader.NODE_DIR_PATH: node_files_folder,
            FSNeptuneCSVLoader.RELATION_DIR_PATH: relationship_files_folder,
            FSNeptuneCSVLoader.SHOULD_DELETE_CREATED_DIR: True,
            FSNeptuneCSVLoader.JOB_PUBLISHER_TAG: 'unique_tag'
        },
        publisher.get_scope(): {
            NeptuneCSVPublisher.NODE_FILES_DIR: node_files_folder,
            NeptuneCSVPublisher.RELATION_FILES_DIR: relationship_files_folder,
            NeptuneCSVPublisher.AWS_S3_BUCKET_NAME: S3_BUCKET_NAME,
            NeptuneCSVPublisher.AWS_BASE_S3_DATA_PATH: S3_DATA_PATH,
            NeptuneCSVPublisher.NEPTUNE_HOST: NEPTUNE_ENDPOINT,
            NeptuneCSVPublisher.AWS_IAM_ROLE_NAME: neptune_iam_role_name,
            NeptuneCSVPublisher.AWS_REGION: AWS_REGION
        },
    })

    DefaultJob(
        conf=job_config,
        task=DefaultTask(
            extractor=GlueExtractor(),
            loader=loader,
            transformer=NoopTransformer()
        ),
        publisher=publisher
    ).launch()

def create_remove_stale_data_job():
    """Run remove stale data from Neptune

    Returns:
        NeptuneStalenessRemovalTask: Neptune stateleness data job
    """

    target_relations = ['DESCRIPTION', 'DESCRIPTION_OF', 'COLUMN', 'COLUMN_OF', 'TABLE', 'TABLE_OF']
    target_nodes = ['Table', 'Column', 'Programmatic_Description', "Schema"]

    staleness_max_pct = 5

    while True:

        try:

            LOGGER.info(f'Delete stale data at threshold - {staleness_max_pct}%')

            job_config = ConfigFactory.from_dict({
                'task.remove_stale_data': {
                    NeptuneStalenessRemovalTask.TARGET_RELATIONS: target_relations,
                    NeptuneStalenessRemovalTask.TARGET_NODES: target_nodes,
                    NeptuneStalenessRemovalTask.STALENESS_CUT_OFF_IN_SECONDS: 86400,  # 1 day
                    NeptuneStalenessRemovalTask.STALENESS_MAX_PCT: staleness_max_pct,
                    'neptune.client': {
                        NeptuneSessionClient.NEPTUNE_HOST_NAME: NEPTUNE_ENDPOINT,
                        NeptuneSessionClient.AWS_REGION: AWS_REGION,
                    }
                }
            })

            job = DefaultJob(
                conf=job_config,
                task=NeptuneStalenessRemovalTask()
            )

            job.launch()

            break

        except Exception as ex:

            LOGGER.error(ex)
            LOGGER.info(f'Increase stale data threshold')

            staleness_max_pct += 5

            if staleness_max_pct == 105:

                break


def create_es_publisher_job(elasticsearch_index_alias='table_search_index',
                            elasticsearch_doc_type_key='table',
                            model_name='databuilder.models.table_elasticsearch_document.TableESDocument',
                            entity_type='table',
                            elasticsearch_mapping=None):
    """
    :param elasticsearch_index_alias:  alias for Elasticsearch used in
                                       amundsensearchlibrary/search_service/config.py as an index
    :param elasticsearch_doc_type_key: name the ElasticSearch index is prepended with. Defaults to `table` resulting in
                                       `table_{uuid}`
    :param model_name:                 the Databuilder model class used in transporting between Extractor and Loader
    :param entity_type:                Entity type handed to the `Neo4jSearchDataExtractor` class, used to determine
                                       Cypher query to extract data from Neo4j. Defaults to `table`.
    :param elasticsearch_mapping:      Elasticsearch field mapping "DDL" handed to the `ElasticsearchPublisher` class,
                                       if None is given (default) it uses the `Table` query baked into the Publisher
    """
    # loader saves data to this location and publisher reads it from here
    extracted_search_data_path = '/var/tmp/amundsen/search_data.json'
    loader = FSElasticsearchJSONLoader()
    extractor = NeptuneSearchDataExtractor()

    task = DefaultTask(
        loader=loader,
        extractor=extractor,
        transformer=NoopTransformer()
    )

    # elastic search client instance
    elasticsearch_client = es

    # unique name of new index in Elasticsearch
    elasticsearch_new_index_key = '{}_'.format(elasticsearch_doc_type_key) + str(uuid.uuid4())

    publisher = ElasticsearchPublisher()

    session = boto3.Session(region_name=AWS_REGION)

    aws_creds = session.get_credentials()
    aws_access_key = aws_creds.access_key
    aws_access_secret = aws_creds.secret_key
    aws_token = aws_creds.token

    job_config = ConfigFactory.from_dict({
        extractor.get_scope(): {
            NeptuneSearchDataExtractor.ENTITY_TYPE_CONFIG_KEY: entity_type,
            NeptuneSearchDataExtractor.MODEL_CLASS_CONFIG_KEY: model_name,
            'neptune.client': {
                NeptuneSessionClient.NEPTUNE_HOST_NAME: NEPTUNE_ENDPOINT,
                NeptuneSessionClient.AWS_REGION: AWS_REGION,
                NeptuneSessionClient.AWS_ACCESS_KEY: aws_access_key,
                NeptuneSessionClient.AWS_SECRET_ACCESS_KEY: aws_access_secret,
                NeptuneSessionClient.AWS_SESSION_TOKEN: aws_token
            }
        },
        'loader.filesystem.elasticsearch.file_path': extracted_search_data_path,
        'loader.filesystem.elasticsearch.mode': 'w',
        publisher.get_scope(): {
            'file_path': extracted_search_data_path,
            'mode': 'r',
            'client': elasticsearch_client,
            'new_index': elasticsearch_new_index_key,
            'doc_type': elasticsearch_doc_type_key,
            'alias': elasticsearch_index_alias
        }
    })

    # only optionally add these keys, so need to dynamically `put` them
    if elasticsearch_mapping:
        job_config.put('publisher.elasticsearch.{}'.format(ElasticsearchPublisher.ELASTICSEARCH_MAPPING_CONFIG_KEY),
                       elasticsearch_mapping)

    job = DefaultJob(
        conf=job_config,
        task=task,
        publisher=ElasticsearchPublisher()
    )

    return job


if __name__ == "__main__":

    logging.basicConfig(level=logging.INFO)

    LOGGER.info('ES Host: ' +  es_host)
    LOGGER.info('Neptune Host: ' + neptune_host)
    LOGGER.info('Neptune Port: ' + str(neptune_port))
    LOGGER.info('Neptune IAM Role Name: ' + neptune_iam_role_name)
    LOGGER.info('S3 Bucket Name: ' + S3_BUCKET_NAME)
    LOGGER.info('S3 Data Path: ' + S3_DATA_PATH)
    LOGGER.info('AWS Region: ' + AWS_REGION)

    logging.info('>>> Running Remove Stale Data Job <<<')

    create_remove_stale_data_job()

    logging.info('>>> Running Glue Extractor <<<')

    run_glue_job('amundsen_glue_extractor')

    logging.info('>>> Running ES Publisher <<<')

    job_es_table = create_es_publisher_job(
        elasticsearch_index_alias='table_search_index',
        elasticsearch_doc_type_key='table',
        entity_type='table',
        model_name='databuilder.models.table_elasticsearch_document.TableESDocument'
    )
    job_es_table.launch()
```

- databases.json

```json
[]
```

- .env

```env
ES_HOST=<ES_HOST>
NEPTUNE_HOST=<NEPTUNE_HOST>
NEPTUNE_PORT=8182
NEPTUNE_IAM_ROLE=<NEPTUNE_IAM_ROLE>
S3_BUCKET_NAME=<S3_BUCKET_NAME>
AWS_REGION=<AWS_REGION>
SECRET_NAME=<SECRET_NAME>
GLUE_DATABASE_IDENTIFIER=<GLUE_DATABASE_IDENTIFIER>
```


Hope this help!

Best Regards.
Bill

**Comment by wey-gu** [comment]
I encountered this issue, too, as I installed data builder from codebase with `python setup.py install`, and after rebase with the main branch, the previous version was not clean up when we simply rerun `python setup.py install`, the way out was to do `pip uninstall amundsen-databuilder` and `pip uninstall amundsen-common` until non of packages existed(there could be multiple versions left, more than once per each package could be required).

Then the expected elastic-related code is up to date w/o this error anymore.
