### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by leotuxbr** [amundsen-io/amundsen#1758]
## Expected Behavior

Start the container with the docker-amundsen-atlas.yml file,
and then run the python3 script example/scripts/sample_data_loader_atlas.py
and create elasticsearch indexes

## Current Behavior

when using docker-amundsen-atlas.yml it starts with elasticsearch:6.8.13
But when I try to use databuilder and run:

python3 example/scripts/sample_data_loader_atlas.py
Indices are not created in elasticsearch

/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py:200: ElasticsearchWarning: the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template
  warnings.warn(message, category=ElasticsearchWarning)
/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py:200: ElasticsearchWarning: [types removal] The parameter include_type_name should be explicitly specified in create index requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', and requests are expected to omit the type name in mapping definitions.
  warnings.warn(message, category=ElasticsearchWarning)
2022-03-08 23:14:52,179 elasticsearch WARNING  PUT http://localhost:9200/table_9334a18b-9105-4251-83a3-fb74ae4f3e4d [status:400 request:0.015s]
2022-03-08 23:14:52,179 databuilder.callback.call_back INFO     No callbacks to notify
Traceback (most recent call last):
  File "example/scripts/sample_data_loader_atlas.py", line 406, in <module>
    job_es_table.launch()
  File "/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/amundsen_databuilder-6.7.1-py3.8.egg/databuilder/job/job.py", line 76, in launch
  File "/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/amundsen_databuilder-6.7.1-py3.8.egg/databuilder/job/job.py", line 72, in launch
  File "/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/amundsen_databuilder-6.7.1-py3.8.egg/databuilder/publisher/base_publisher.py", line 40, in publish
  File "/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/amundsen_databuilder-6.7.1-py3.8.egg/databuilder/publisher/base_publisher.py", line 37, in publish
  File "/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/amundsen_databuilder-6.7.1-py3.8.egg/databuilder/publisher/elasticsearch_publisher.py", line 93, in publish_impl
  File "/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 145, in create
    return self.transport.perform_request(
  File "/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 466, in perform_request
    raise e
  File "/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 427, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 291, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/user/amundsen-new/amundsen/databuilder/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 328, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [schema : {analyzer=simple, type=text, fields={raw={type=keyword}}}] [cluster : {analyzer=simple, type=text, fields={raw={type=keyword}}}] [description : {analyzer=simple, type=text}] [display_name : {type=keyword}] [column_descriptions : {analyzer=simple, type=text}] [programmatic_descriptions : {analyzer=simple, type=text}] [tags : {type=keyword}] [badges : {type=keyword}] [database : {analyzer=simple, type=text, fields={raw={type=keyword}}}] [total_usage : {type=long}] [name : {analyzer=simple, type=text, fields={raw={type=keyword}}}] [last_updated_timestamp : {format=epoch_second, type=date}] [unique_usage : {type=long}] [column_names : {analyzer=simple, type=text, fields={raw={normalizer=column_names_normalizer, type=keyword}}}] [key : {type=keyword}]')

## Possible Solution
Is it possible to have an atlas compatible version of search, frontend and metadata?
Even upgrading to elasticsearch 7 doesn't seem to work properly.

## Steps to Reproduce
1. docker-compose -f docker-amundsen-atlas.yml up
3. wait for all services to start
4.
```
cd databuilder
source venv/bin/activate
pip3 install --upgrade pip
pip3 install -r requirements.txt
python3 setup.py install
pip install apache_atlas atlasclient
python3 example/scripts/sample_data_loader_atlas.py 
```

## Your Environment

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by leotuxbr** [comment]
issues resolved by setting the versions to: 
amundsen-frontend:3.12.0
amundsendev/amundsen-metadata:3.9.0
amundsendev/amundsen-search:2.11.1
elasticsearch:8.0.0

**Comment by feng-tao** [comment]
@leotuxbr how about you create a pr to update that dockercompose file with the right version?
