### ISSUE TITLE
Swagger example for POST /document_table in search service generates 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by hinnefe2** [amundsen-io/amundsen#176]
First of all, thank you for open-sourcing this tool, it looks really neat!

I'm running into an issue with the search service: when I try to POST to /document_table using the example from the Swagger docs it generates a 500 INTERNAL SERVER ERROR response.

In case it's relevant, these tests were all done after running `docker-compose -f docker-amundsen.yml up` and loading the sample data with `python3 example/scripts/sample_data_loader.py`

```
In [36]: import sys

In [37]: import requests

In [38]: print(sys.version)
3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]

In [39]: print(requests.__version__)
2.18.4

# copied from http://localhost:5001/apidocs/#/document_table/post_document_table
In [40]: example_data = {
    ...:   "data": [
    ...:     {
    ...:       "cluster": "cluster",
    ...:       "column_names": [
    ...:         "col1",
    ...:         "col2"
    ...:       ],
    ...:       "database": "db",
    ...:       "description": "this table holds revenue data",
    ...:       "key": "cluster://schema.db/table_name",
    ...:       "last_updated_epoch": 1568814420,
    ...:       "name": "table_name",
    ...:       "schema_name": "schema",
    ...:       "tags": [
    ...:         "tag2",
    ...:         "tag1"
    ...:       ]
    ...:     }
    ...:   ]
    ...: }

In [41]: requests.post('http://localhost:5001/document_table', json=example_data)
Out[41]: <Response [500]>

In [42]: requests.post('http://localhost:5001/document_table', data=example_data)
Out[42]: <Response [500]>
```

The stack trace for the first approach (using `json` to [pass string-encoded data](https://stackoverflow.com/a/26344315) is)
```
amundsensearch      | ERROR:flask.app:Exception on /document_table [POST]
amundsensearch      | Traceback (most recent call last):
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 418, in resolve_fragment
amundsensearch      |     document = document[part]
amundsensearch      | KeyError: 'components'
amundsensearch      |
amundsensearch      | During handling of the above exception, another exception occurred:
amundsensearch      |
amundsensearch      | Traceback (most recent call last):
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1811, in full_dispatch_request
amundsensearch      |     rv = self.preprocess_request()
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2087, in preprocess_request
amundsensearch      |     rv = func()
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/flasgger/base.py", line 636, in before_request
amundsensearch      |     format_checker=self.format_checker)
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 541, in validate
amundsensearch      |     cls(schema, *args, **kwargs).validate(instance)
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 129, in validate
amundsensearch      |     for error in self.iter_errors(*args, **kwargs):
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
amundsensearch      |     for error in errors:
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/_validators.py", line 304, in properties_draft4
amundsensearch      |     schema_path=property,
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 121, in descend
amundsensearch      |     for error in self.iter_errors(instance, schema):
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
amundsensearch      |     for error in errors:
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/_validators.py", line 55, in items
amundsensearch      |     for error in validator.descend(item, items, path=index):
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 121, in descend
amundsensearch      |     for error in self.iter_errors(instance, schema):
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
amundsensearch      |     for error in errors:
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/_validators.py", line 212, in ref
amundsensearch      |     scope, resolved = validator.resolver.resolve(ref)
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 375, in resolve
amundsensearch      |     return url, self._remote_cache(url)
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 387, in resolve_from_url
amundsensearch      |     return self.resolve_fragment(document, fragment)
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 421, in resolve_fragment
amundsensearch      |     "Unresolvable JSON pointer: %r" % fragment
amundsensearch      | jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'components/schemas/TableFields'
````

The stack trace for the second approach (using `data` to pass form-encoded data) is
```
amundsensearch      | ERROR:flask.app:Exception on /document_table [POST]
amundsensearch      | Traceback (most recent call last):
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
amundsensearch      |     rv = self.dispatch_request()
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
amundsensearch      |     return self.view_functions[rule.endpoint](**req.view_args)
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
amundsensearch      |     resp = resource(*args, **kwargs)
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view
amundsensearch      |     return self.dispatch_request(*args, **kwargs)
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
amundsensearch      |     resp = meth(*args, **kwargs)
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/flasgger/utils.py", line 249, in wrapper
amundsensearch      |     return function(*args, **kwargs)
amundsensearch      |   File "/app/search_service/api/document.py", line 121, in post
amundsensearch      |     return super().post()
amundsensearch      |   File "/app/search_service/api/document.py", line 62, in post
amundsensearch      |     data = self.schema(many=True, unknown='EXCLUDE').loads(args.get('data'))
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 729, in loads
amundsensearch      |     data = self.opts.render_module.loads(json_data, **kwargs)
amundsensearch      |   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
amundsensearch      |     return _default_decoder.decode(s)
amundsensearch      |   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
amundsensearch      |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
amundsensearch      |   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
amundsensearch      |     raise JSONDecodeError("Expecting value", s, err.value) from None
amundsensearch      | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by feng-tao** [comment]
cc @swatro 
currently we are a bit hand full. If you have time to help take a look(even submit a pr to fix), that will be great. Otherwise we will take a look once we get to it.

**Comment by verdan** [comment]
https://github.com/amundsen-io/amundsensearchlibrary/pull/188
