### ISSUE TITLE
Python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by FelipeArruda** [amundsen-io/amundsen#1775]
I'm trying to install Amundsen on docker running on Windows 10. I'm getting an error while run a docker-compose using atlas.

## Expected Behavior

Install success

## Current Behavior

Getting erro where execute: docker-compose -f docker-amundsen-atlas.yml up

## Steps to Reproduce

1. Clone the repo
2. Execute: docker-compose -f docker-amundsen-atlas.yml up (get an error in this step)

- Error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      /bin/sh: 1: npm: not found
      ERROR:root:npm must be available
      /bin/sh: 1: npm: not found
      /app/setup.py:30: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
        logging.warn('Installation of npm dependencies failed')
      WARNING:root:Installation of npm dependencies failed
      /app/setup.py:31: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
        logging.warn(str(e))
      WARNING:root:Command '['npm install']' returned non-zero exit status 127.
      error in amundsen-frontend setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
1 error occurred:
        * Status: The command '/bin/sh -c pip3 install -e .' returned a non-zero code: 1, Code: 1

## Screenshots (if appropriate)
![Screenshot_7](https://user-images.githubusercontent.com/5818475/159786479-38eed1ac-f548-4f2b-a765-4e5195557c18.png)
## Your Environment

* Amunsen version used: 6.7.4
* Data warehouse stores: none yet
* Deployment (k8s or native): native
* Link to your fork or repository:

**Comment by ceaser008** [comment]
same issue in manjaro
![Screenshot_20220416_085320](https://user-images.githubusercontent.com/93041325/163659247-bbd10ad1-c58e-4878-b4f8-0daa138a608d.png)
o

**Comment by mcavalcante28** [comment]
Hi @FelipeArruda. What image are you using for run python? 
I get the same issue usgin python:3.10.2-alpine, but not for python:3.10.2-slim.

**Comment by FelipeArruda** [comment]
> 3.10.2

Hi @mcavalcante28 its 3.10 python version.

**Comment by micfun123** [comment]
using Python 3.10.4 and getting this problem as well. Is there a fix?

**Comment by HridoyHazard** [comment]
having the same issue ? any fix ?

**Comment by FelipeArruda** [comment]
@feng-tao Can you help?

**Comment by micfun123** [comment]
@FelipeArruda  use a python version Lowe that 3.10 . I got it to work on 3.9

**Comment by HridoyHazard** [comment]
thanks mine got worked on 3.7

**Comment by FelipeArruda** [comment]
@micfun123 and @HridoyHazard, Did you try with Neo4j Backend or Atlas?

I'm trying to run Atlas and getting the same erro with python 3.6

**Comment by FelipeArruda** [comment]
> no I just installed normal python package

Srry man. Didn't you use this commands to start docker?

# For Neo4j Backend
$ docker-compose -f docker-amundsen.yml up

# For Atlas
$ docker-compose -f docker-amundsen-atlas.yml up

None?

**Comment by Parvat-R** [comment]
Try updating the setuptools package using `pip install --upgrade setuptools`

**Comment by Jiboku-Oluwatunmise** [comment]
I'm also having this issue any help

**Comment by drunksoul2021** [comment]
> I'm trying to install Amundsen on docker running on Windows 10. I'm getting an error while run a docker-compose using atlas.
> 
> ## Expected Behavior
> Install success
> 
> ## Current Behavior
> Getting erro when execute: docker-compose -f docker-amundsen-atlas.yml up
> 
> ## Steps to Reproduce
> 1. Clone the repo
> 2. Execute: docker-compose -f docker-amundsen-atlas.yml up (get an error in this step)
> 
> * Error:
>   error: subprocess-exited-with-error
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [10 lines of output]
>   /bin/sh: 1: npm: not found
>   ERROR:root:npm must be available
>   /bin/sh: 1: npm: not found
>   /app/setup.py:30: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
>   logging.warn('Installation of npm dependencies failed')
>   WARNING:root:Installation of npm dependencies failed
>   /app/setup.py:31: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
>   logging.warn(str(e))
>   WARNING:root:Command '['npm install']' returned non-zero exit status 127.
>   error in amundsen-frontend setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
>   [end of output]
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details. 1 error occurred: * Status: The command '/bin/sh -c pip3 install -e .' returned a non-zero code: 1, Code: 1
> 
> ## Screenshots (if appropriate)
> ![Screenshot_7](https://user-images.githubusercontent.com/5818475/159786479-38eed1ac-f548-4f2b-a765-4e5195557c18.png)
> 
> ## Context
> ## Your Environment
> * Amunsen version used: 6.7.4
> * Data warehouse stores: none yet
> * Deployment (k8s or native): native
> * Link to your fork or repository:

try myway ,it work for me.
https://blog.csdn.net/drunk_soul/article/details/126336272

**Comment by Akanmu01** [comment]
upon deploying django on vercel server i was unable to use sqlite so i decided to use mysql but i got this error

Preparing metadata (setup.py): finished with status 'error'
--
15:12:04.162 | error: subprocess-exited-with-error
15:12:04.162 |  
15:12:04.162 | × python setup.py egg_info did not run successfully.
15:12:04.163 | │ exit code: 1
15:12:04.163 | ╰─> [16 lines of output]
15:12:04.163 | /bin/sh: mysql_config: command not found
15:12:04.163 | /bin/sh: mariadb_config: command not found
15:12:04.163 | /bin/sh: mysql_config: command not found
15:12:04.164 | Traceback (most recent call last):
15:12:04.164 | File "<string>", line 2, in <module>
15:12:04.164 | File "<pip-setuptools-caller>", line 34, in <module>
15:12:04.164 | File "/tmp/pip-install-8irz5g1t/mysqlclient_c5f7aa23355741f3ba46173c81f54328/setup.py", line 15, in <module>
15:12:04.165 | metadata, options = get_config()
15:12:04.165 | File "/tmp/pip-install-8irz5g1t/mysqlclient_c5f7aa23355741f3ba46173c81f54328/setup_posix.py", line 70, in get_config
15:12:04.165 | libs = mysql_config("libs")
15:12:04.165 | File "/tmp/pip-install-8irz5g1t/mysqlclient_c5f7aa23355741f3ba46173c81f54328/setup_posix.py", line 31, in mysql_config
15:12:04.166 | raise OSError("{} not found".format(_mysql_config_path))
15:12:04.166 | OSError: mysql_config not found
15:12:04.166 | mysql_config --version
15:12:04.166 | mariadb_config --version
15:12:04.166 | mysql_config --libs
15:12:04.166 | [end of output]
15:12:04.166 |  
15:12:04.167 | note: This error originates from a subprocess, and is likely not a problem with pip.
15:12:04.167 | error: metadata-generation-failed
15:12:04.167 |  
15:12:04.167 | × Encountered error while generating package metadata.
15:12:04.167 | ╰─> See above for output.
15:12:04.168 |  
15:12:04.168 | note: This is an issue with the package mentioned above, not pip.
15:12:04.168 | hint: See above for details.
15:12:04.437 | Traceback (most recent call last):
15:12:04.438 | File "/vercel/path0/manage.py", line 11, in main
15:12:04.438 | from django.core.management import execute_from_command_line
15:12:04.438 | ModuleNotFoundError: No module named 'django'
15:12:04.438 |  
15:12:04.439 | The above exception was the direct cause of the following exception:
15:12:04.439 |  
15:12:04.439 | Traceback (most recent call last):
15:12:04.439 | File "/vercel/path0/manage.py", line 22, in <module>
15:12:04.439 | main()
15:12:04.439 | File "/vercel/path0/manage.py", line 13, in main
15:12:04.439 | raise ImportError(
15:12:04.440 | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
15:12:04.453 | Traceback (most recent call last):
15:12:04.453 | File "/vercel/path0/manage.py", line 11, in main
15:12:04.454 | from django.core.management import execute_from_command_line
15:12:04.454 | ModuleNotFoundError: No module named 'django'
15:12:04.454 |  
15:12:04.454 | The above exception was the direct cause of the following exception:
15:12:04.454 |  
15:12:04.454 | Traceback (most recent call last):
15:12:04.455 | main()
15:12:04.455 | File "/vercel/path0/manage.py", line 13, in main
15:12:04.455 | raise ImportError(
15:12:04.455 | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
15:12:04.470 | Traceback (most recent call last):
15:12:04.470 | File "/vercel/path0/manage.py", line 11, in main
15:12:04.470 | from django.core.management import execute_from_command_line
15:12:04.471 | ModuleNotFoundError: No module named 'django'
15:12:04.471 |  
15:12:04.471 | The above exception was the direct cause of the following exception:
15:12:04.471 |  
15:12:04.471 | Traceback (most recent call last):
15:12:04.472 | File "/vercel/path0/manage.py", line 22, in <module>
15:12:04.472 | main()
15:12:04.472 | File "/vercel/path0/manage.py", line 13, in main
15:12:04.472 | raise ImportError(
15:12:04.472 | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
15:12:04.488 | Error: Command "./build_files.sh" exited with 1

**Comment by fireragnarous** [comment]
I also met the same problem on my Centos7 linux server, is there any solution available now? Thanks.

**Comment by fireragnarous** [comment]
I have tried to solve this problem I mentioned above on linux using the following changed dockfile, I hope it can be helpful to you. I tried to install amundsen in China so part of the code is added to use a mirror source. 
### Changed Dockerfile.fronted.local
ARG METADATASERVICE_BASE
ARG SEARCHSERVICE_BASE

FROM node:12-slim as node-stage
WORKDIR /app/amundsen_application/static

COPY ./frontend/amundsen_application/static/package.json /app/amundsen_application/static/package.json
COPY ./frontend/amundsen_application/static/package-lock.json /app/amundsen_application/static/package-lock.json
RUN npm config set registry https://registry.npm.taobao.org
#RUN npm install -g cnpm --registry http://mirrors.cloud.tencent.com/npm/
RUN npm install -g cnpm --registry https://registry.npm.taobao.org
RUN npm install

COPY ./frontend/amundsen_application/static/ /app/amundsen_application/static/
RUN cnpm rebuild node-sass
RUN cnpm run dev-build

COPY ./frontend /app

FROM python:3.7-slim
WORKDIR /app

COPY ./frontend /app
COPY requirements-dev.txt /app/requirements-dev.txt
COPY requirements-common.txt /app/requirements-common.txt
RUN pip3 install -r requirements-dev.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
RUN pip3 install -r requirements-common.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
RUN pip3 install --upgrade setuptools
COPY --from=node-stage /app /app

RUN pip install --upgrade pip
#RUN pip3 install -e .

COPY requirements-dev.txt /app/requirements-dev.txt
COPY requirements-common.txt /app/requirements-common.txt

RUN python3 setup.py install

ENTRYPOINT [ "python3" ]
CMD [ "amundsen_application/wsgi.py" ]

**Comment by lijm1206** [comment]
是

**Comment by dazzafact** [comment]
Same issue with Python3.8

**Comment by kallonbundu** [comment]
on the same deployment problem
