### ISSUE TITLE
Sample Data Loaders - Elastic Search publish fails

### ISSUE THREAD

**Issue by s-nachimuthu** [amundsen-io/amundsen#1805]
```
a_loader.py
WARNING:elasticsearch:PUT http://localhost:9200/table_930d0777-697d-4c96-b6b2-1d73c79356b0 [status:400 request:0.040s]
Traceback (most recent call last):
  File "example/scripts/sample_data_loader.py", line 407, in <module>
    job_es_table.launch()
  File "/home/test/amundsen/databuilder/venv/lib64/python3.6/site-packages/amundsen_databuilder-6.7.4-py3.6.egg/databuilder/job/job.py", line 76, in launch
  File "/home/test/amundsen/databuilder/venv/lib64/python3.6/site-packages/amundsen_databuilder-6.7.4-py3.6.egg/databuilder/job/job.py", line 72, in launch
  File "/home/test/amundsen/databuilder/venv/lib64/python3.6/site-packages/amundsen_databuilder-6.7.4-py3.6.egg/databuilder/publisher/base_publisher.py", line 40, in publish
  File "/home/test/amundsen/databuilder/venv/lib64/python3.6/site-packages/amundsen_databuilder-6.7.4-py3.6.egg/databuilder/publisher/base_publisher.py", line 37, in publish
  File "/home/test/amundsen/databuilder/venv/lib64/python3.6/site-packages/amundsen_databuilder-6.7.4-py3.6.egg/databuilder/publisher/elasticsearch_publisher.py", line 93, in publish_impl
  File "/home/test/amundsen/databuilder/venv/lib64/python3.6/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/test/amundsen/databuilder/venv/lib64/python3.6/site-packages/elasticsearch/client/indices.py", line 146, in create
    "PUT", _make_path(index), params=params, headers=headers, body=body
  File "/home/test/amundsen/databuilder/venv/lib64/python3.6/site-packages/elasticsearch/transport.py", line 466, in perform_request
    raise e
  File "/home/test/amundsen/databuilder/venv/lib64/python3.6/site-packages/elasticsearch/transport.py", line 434, in perform_request
    timeout=timeout,
  File "/home/test/amundsen/databuilder/venv/lib64/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 291, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/test/amundsen/databuilder/venv/lib64/python3.6/site-packages/elasticsearch/connection/base.py", line 329, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [table : {properties={schema={analyzer=simple, type=text, fields={raw={type=keyword}}}, cluster={analyzer=simple, type=text, fields={raw={type=keyword}}}, description={analyzer=simple, type=text}, display_name={type=keyword}, column_descriptions={analyzer=simple, type=text}, programmatic_descriptions={analyzer=simple, type=text}, tags={type=keyword}, badges={type=keyword}, database={analyzer=simple, type=text, fields={raw={type=keyword}}}, total_usage={type=long}, name={analyzer=simple, type=text, fields={raw={type=keyword}}}, last_updated_timestamp={format=epoch_second, type=date}, unique_usage={type=long}, column_names={analyzer=simple, type=text, fields={raw={normalizer=column_names_normalizer, type=keyword}}}, key={type=keyword}}}]')

```

**Comment by s-nachimuthu** [comment]
This seems to happen after ES upgraded to 8.0. Can you give sample data loader which works with the latest version 6.7.4?

**Comment by Amandianeze** [comment]
Agreed, having the same issue

**Comment by mgorsk1** [comment]
upgrade to latest versions of all components should resolve it

**Comment by minizhu7** [comment]
ES upgrade to 8.1.0 could resolve it
