### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by hituhe2** [amundsen-io/amundsen#1825]
Trying to use sample_teradata_loader.py to access Teradata. Getting error.

## Expected Behavior

Should have accessed Teradata installation . This code works fine

```
import sqlalchemy
user = '...'
host = '...'
port = '...'
password = '...'
db = '...'

td_engine = sqlalchemy.create_engine('teradatasql://'+ user +':' + password + '@'+ host + ':1025/')
# execute sql
sql = 'select * from demo.tbl'
result = td_engine.execute(sql)
i = 0
for row in result:
  if ( i <5):
    print(row)
  else:
    break
  i = i + 1


```
## Current Behavior

Throwing error

```
aceback (most recent call last):
  File "/home/ec2-user/amundsen/databuilder/example/scripts/sample_teradatatopti                                                                             mized_loader.py", line 168, in <module>
    loading_job.launch()
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-6.7.1-py3.7.                                                                             egg/databuilder/job/job.py", line 76, in launch
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-6.7.1-py3.7.                                                                             egg/databuilder/job/job.py", line 64, in launch
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-6.7.1-py3.7.                                                                             egg/databuilder/job/job.py", line 51, in _init
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-6.7.1-py3.7.                                                                             egg/databuilder/task/task.py", line 45, in init
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-6.7.1-py3.7.                                                                             egg/databuilder/extractor/sql_alchemy_extractor.py", line 31, in init
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-6.7.1-py3.7.                                                                             egg/databuilder/extractor/sql_alchemy_extractor.py", line 56, in _get_connection
  File "<string>", line 2, in create_engine
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/deprecations.py                                                                             ", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/create.py", l                                                                             ine 534, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/url.py", line                                                                              661, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py"                                                                             , line 344, in load
    "Can't load plugin: %s:%s" % (self.group, name)
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:teradat                                                                             asql
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-6.7.1-py3.7.                                                                             egg/databuilder/utils/closer.py", line 47, in close
  File "/usr/local/lib/python3.7/site-packages/amundsen_databuilder-6.7.1-py3.7.                                                                             egg/databuilder/extractor/sql_alchemy_extractor.py", line 43, in close
AttributeError: 'SQLAlchemyExtractor' object has no attribute 'connection'

```

## Possible Solution

The problem is , in _/usr/local/lib/python3.7/site-packages/sqlalchemy_teradata-0.9.0.dev0.dist-info/entry_points.txt_ , there is no dialect mentioned for **teradatasql**
3. What would be a value for teradatasql ? Existing value is only for teradata

**[sqlalchemy.dialects]
teradata = sqlalchemy_teradata.dialect:TeradataDialect**

## Steps to Reproduce

Start with sample teradata loader provided in **amundsen/databuilder/example/scripts/sample_teradata_loader.py** and add your teradata details.

1. Run the loader, it will result in _"Can't load plugin: %s:%s" % (self.group, name)
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:teradatasql_

## Context

Trying to write Teradata connector, not happening

/usr/local/lib/python3.7/site-packages/sqlalchemy_teradata-0.9.0.dev0.dist-info/entry_points.txt  has only this entry
```
[sqlalchemy.dialects]
teradata = sqlalchemy_teradata.dialect:TeradataDialect
```

## Your Environment

* Amunsen version used: Latest
* Data warehouse stores: Teradata
* Deployment (k8s or native): Native
* Link to your fork or repository:

**Comment by hituhe2** [comment]
I made some progress.  Now the error is the following , current_database() does not exist as any function as I confirmed by running the SQL separately from a simple python program

            **f"extractor.teradata_metadata.{TeradataMetadataExtractor.USE_CATALOG_AS_CLUSTER_NAME}": True,**


 ```
sqlalchemy.exc.OperationalError: (teradatasql.OperationalError) [Version 17.10.0.12] [Session 124545] [Teradata Database] [Error 3706] Syntax error: expected something between '(' and ')'
SELECT
                current_database() as td_cluster,
                c.DatabaseName as schema,
                c.TableName as name,
                c.CommentString as description,
                d.ColumnName as col_name,
                d.ColumnType as col_type,
                d.CommentString as col_description,
                d.ColumnId as col_sort_order
            FROM dbc.Tables c, dbc.Columns d
            WHERE c.DatabaseName = d.DatabaseName AND c.TableName = d.TableName
            AND
c.DatabaseName = 'Default'
 ORDER by cluster_a, schema, name, col_sort_order;
```

**Comment by hituhe2** [comment]
With             **f"extractor.teradata_metadata.{TeradataMetadataExtractor.USE_CATALOG_AS_CLUSTER_NAME}": False,**
the error is obvious, in order by clause.

_sqlalchemy.exc.OperationalError: (teradatasql.OperationalError) [Version 17.10.0.12] [Session 124546] [Teradata Database] [Error 5628] Column cluster_a not found in dbc.c or dbc.d_

```
SELECT
                'master' as td_cluster,
                c.DatabaseName as schema,
                c.TableName as name,
                c.CommentString as description,
                d.ColumnName as col_name,
                d.ColumnType as col_type,
                d.CommentString as col_description,
                d.ColumnId as col_sort_order
            FROM dbc.Tables c, dbc.Columns d
            WHERE c.DatabaseName = d.DatabaseName AND c.TableName = d.TableName
            AND
c.DatabaseName = 'Default'

            ORDER by cluster_a, schema, name, col_sort_order;

```
