### ISSUE TITLE
Search broken: marshmallow ValidationError

### ISSUE THREAD

**Issue by sagar-raythatha** [amundsen-io/amundsen#1860]
## Expected Behavior
Search should return values which is being searched in the search bar

## Current Behavior
It is not getting any response to the search query.

Below is the error log:
`
Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 467, in wrapper resp = resource(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view return self.dispatch_request(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 582, in dispatch_request resp = meth(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/flasgger/utils.py", line 273, in wrapper return function(*args, **kwargs) File "/app/search_service/api/search.py", line 33, in post request_data = SearchRequestSchema().loads(json.dumps(request.get_json())) File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 756, in loads return self.load(data, many=many, partial=partial, unknown=unknown) File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load data, many=many, partial=partial, unknown=unknown, postprocess=True File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 904, in _do_load raise exc marshmallow.exceptions.ValidationError: {'highlight_options': ['Unknown field.']}
`

## Possible Solution
It looks like recently there are changes in common-0.27.x on the Highlight options:
https://github.com/amundsen-io/amundsen/blame/common-0.27.0/common/amundsen_common/models/search.py#L42

And search is using amundsen-common-0.27.x and it might be causing an issue.

## Context
Search functionality has stopped working

## Your Environment

* Amunsen version used:
- amundsendev/amundsen-search:3.0.0

**Comment by sagar-raythatha** [comment]
@allisonsuarez any solution for this?

**Comment by allisonsuarez** [comment]
My bad let me make releases with the patch for this right now!

**Comment by allisonsuarez** [comment]
get frontend 4.0.1 and search 3.1.1

**Comment by allisonsuarez** [comment]
My bad I will put out releases for this patch

**Comment by allisonsuarez** [comment]
Okay bump to frotend 4.1.2 and search 4.0.2

**Comment by sagar-raythatha** [comment]
@allisonsuarez  it looks like it has not resolved my issue.

I am using search-3.0.0 and it is broken. Do you feel that the changes made in amundsen-common:0.27.0 can contribute to this issue of highlight option?
https://github.com/amundsen-io/amundsen/pull/1819

**Comment by sagar-raythatha** [comment]
I have updated to search 4.0.2, but still having the same issue.

**Comment by allisonsuarez** [comment]
You have to update frontend too, have you done that?

**Comment by sagar-raythatha** [comment]
I am trying to update that too. However, I am getting below error while upgrading frontend.

ModuleNotFoundError: No module named 'google.protobuf'

I have also tried adding protobuf & protobuf3 in requirements.txt but then also it is giving the same error. Any idea on this?

**Comment by allisonsuarez** [comment]
Oh that's odd I haven't seen this at a;; @feng-tao any ideas?

**Comment by owen-leung-mox** [comment]
I'm using search 3.1.0 and it's broken also. I fixed the versioning to use `amundsen-common==0.26.0` and it's working again
