### ISSUE TITLE
Unable to load sample data

### ISSUE THREAD

**Issue by creativeHats** [amundsen-io/amundsen#1909]
Followed all the steps with latest amudsen installation as per https://www.amundsen.io/amundsen/installation/.

All docker containers are up and running
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/20940179/175453699-e9a6dc92-a93b-4137-975b-8ca1e64e7c6e.png">

Getting following error
**python3 example/scripts/sample_data_loader.py**
```
WARNING:databuilder.publisher.elasticsearch_publisher:ElasticsearchPublisher is being deprecated in favor of using SearchMetadatatoElasticasearchTask            which publishes ES metadata with mappings compatible with amundsensearch >= 4.0.0
WARNING:elasticsearch:PUT http://localhost:9200/table_e52929b6-2cd3-4c52-9d07-37094e5db5e5 [status:400 request:0.036s]
Traceback (most recent call last):
  File "example/scripts/sample_data_loader.py", line 407, in <module>
    job_es_table.launch()
  File "/opt/amundsen/venv/lib/python3.6/site-packages/amundsen_databuilder-6.9.0-py3.6.egg/databuilder/job/job.py", line 76, in launch
  File "/opt/amundsen/venv/lib/python3.6/site-packages/amundsen_databuilder-6.9.0-py3.6.egg/databuilder/job/job.py", line 72, in launch
  File "/opt/amundsen/venv/lib/python3.6/site-packages/amundsen_databuilder-6.9.0-py3.6.egg/databuilder/publisher/base_publisher.py", line 40, in publish
  File "/opt/amundsen/venv/lib/python3.6/site-packages/amundsen_databuilder-6.9.0-py3.6.egg/databuilder/publisher/base_publisher.py", line 37, in publish
  File "/opt/amundsen/venv/lib/python3.6/site-packages/amundsen_databuilder-6.9.0-py3.6.egg/databuilder/publisher/elasticsearch_publisher.py", line 104, in publish_impl
  File "/opt/amundsen/venv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/opt/amundsen/venv/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 146, in create
    "PUT", _make_path(index), params=params, headers=headers, body=body
  File "/opt/amundsen/venv/lib/python3.6/site-packages/elasticsearch/transport.py", line 466, in perform_request
    raise e
  File "/opt/amundsen/venv/lib/python3.6/site-packages/elasticsearch/transport.py", line 434, in perform_request
    timeout=timeout,
  File "/opt/amundsen/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 291, in perform_request
    self._raise_error(response.status, raw_data)
  File "/opt/amundsen/venv/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 329, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [table : {properties={schema={analyzer=simple, type=text, fields={raw={type=keyword}}}, cluster={analyzer=simple, type=text, fields={raw={type=keyword}}}, description={analyzer=simple, type=text}, display_name={type=keyword}, column_descriptions={analyzer=simple, type=text}, programmatic_descriptions={analyzer=simple, type=text}, tags={type=keyword}, badges={type=keyword}, database={analyzer=simple, type=text, fields={raw={type=keyword}}}, total_usage={type=long}, name={analyzer=simple, type=text, fields={raw={type=keyword}}}, last_updated_timestamp={format=epoch_second, type=date}, unique_usage={type=long}, column_names={analyzer=simple, type=text, fields={raw={normalizer=column_names_normalizer, type=keyword}}}, key={type=keyword}}}]')
```

**Output of pip3 freeze**
```
alembic==1.7.7
amundsen-common==0.24.1
amundsen-databuilder==6.9.0
amundsen-rds==0.0.6
atomicwrites==1.4.0
attrs==21.4.0
certifi==2022.6.15
charset-normalizer==2.0.12
click==8.0.4
dataclasses==0.8
elasticsearch==7.17.4
elasticsearch-dsl==7.4.0
Flask==2.0.3
freezegun==1.2.1
ghp-import==2.1.0
httplib2==0.20.4
idna==3.3
importlib-metadata==4.8.3
importlib-resources==5.4.0
itsdangerous==2.0.1
Jinja2==3.0.3
jsonref==0.2
Mako==1.1.6
Markdown==3.3.7
MarkupSafe==2.0.1
marshmallow==3.14.1
marshmallow3-annotations==1.1.0
mergedeep==1.3.4
mkdocs==1.3.0
mkdocs-material==8.2.11
mkdocs-material-extensions==1.0.3
mkdocs-redirects==1.0.4
more-itertools==8.13.0
neo4j-driver==1.7.6
neobolt==1.7.17
neotime==1.7.4
numpy==1.19.5
packaging==21.3
pandas==1.1.5
pluggy==1.0.0
py==1.11.0
Pygments==2.11.2
pyhocon==0.3.59
pymdown-extensions==9.1
pyparsing==2.4.7
python-dateutil==2.8.2
pytz==2022.1
PyYAML==6.0
pyyaml_env_tag==0.1
requests==2.27.1
responses==0.17.0
retrying==1.3.3
six==1.16.0
SQLAlchemy==1.3.24
statsd==3.3.0
typing_extensions==4.1.1
unicodecsv==0.14.1
Unidecode==1.3.4
urllib3==1.26.9
watchdog==2.1.9
WerkzeuMarkupSafe 2.0.1 to easy-ins

```

**Comment by xfiderek** [comment]
Hi. 
1. Can you try pulling the most recent changes and reinstalling the databuilder? There is a new version now (6.10.0)
2. You can also try with different version of python. From your logs it looks like you are using python 3.6. The script works fine for me and I am using 3.8.10.

**Comment by glpcf** [comment]
1:see https://github.com/amundsen-io/amundsen/tree/main/databuilder#requirements, only support elasticsearch 6.x (currently it doesn't support 7.x),when I replace elasticsearch8 to es 6.8.23,error changed to
WARNING:elasticsearch:POST http://localhost:9200/_bulk [status:400 request:0.008s]
Traceback (most recent call last):
  File "1.py", line 405, in <module>
    job_es_table.launch()
  File "/root/amundsen-databuilder-6.8.0/databuilder/databuilder/job/job.py", line 79, in launch
    raise e
  File "/root/amundsen-databuilder-6.8.0/databuilder/databuilder/job/job.py", line 75, in launch
    self.publisher.publish()
  File "/root/amundsen-databuilder-6.8.0/databuilder/databuilder/publisher/base_publisher.py", line 40, in publish
    raise e
  File "/root/amundsen-databuilder-6.8.0/databuilder/databuilder/publisher/base_publisher.py", line 37, in publish
    self.publish_impl()
  File "/root/amundsen-databuilder-6.8.0/databuilder/databuilder/publisher/elasticsearch_publisher.py", line 124, in publish_impl
    self.elasticsearch_client.bulk(bulk_actions)
  File "/root/glp/lib64/python3.6/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/root/glp/lib64/python3.6/site-packages/elasticsearch/client/__init__.py", line 477, in bulk
    body=body,
  File "/root/glp/lib64/python3.6/site-packages/elasticsearch/transport.py", line 466, in perform_request
    raise e
  File "/root/glp/lib64/python3.6/site-packages/elasticsearch/transport.py", line 434, in perform_request
    timeout=timeout,
  File "/root/glp/lib64/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 291, in perform_request
    self._raise_error(response.status, raw_data)
  File "/root/glp/lib64/python3.6/site-packages/elasticsearch/connection/base.py", line 329, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: type is missing;2: type is missing;3: type is missing;4: type is missing;5: type is missing;6: type is missing;')
2.I change code databuilder/databuilder/publisher/elasticsearch_publisher.py : 109
 index_row = dict(index=dict(_index=self.elasticsearch_new_index,_type=self.elasticsearch_type))
to add _type 
it is ok

**Comment by togidoto** [comment]
> 1:see https://github.com/amundsen-io/amundsen/tree/main/databuilder#requirements, only support elasticsearch 6.x (currently it doesn't support 7.x),when I replace elasticsearch8 to es 6.8.23,error changed to
> 
> ```
> WARNING:elasticsearch:POST http://localhost:9200/_bulk [status:400 request:0.008s]
> Traceback (most recent call last):
>   File "1.py", line 405, in <module>
>     job_es_table.launch()
>   File "/root/amundsen-databuilder-6.8.0/databuilder/databuilder/job/job.py", line 79, in launch
>     raise e
>   File "/root/amundsen-databuilder-6.8.0/databuilder/databuilder/job/job.py", line 75, in launch
>     self.publisher.publish()
>   File "/root/amundsen-databuilder-6.8.0/databuilder/databuilder/publisher/base_publisher.py", line 40, in publish
>     raise e
>   File "/root/amundsen-databuilder-6.8.0/databuilder/databuilder/publisher/base_publisher.py", line 37, in publish
>     self.publish_impl()
>   File "/root/amundsen-databuilder-6.8.0/databuilder/databuilder/publisher/elasticsearch_publisher.py", line 124, in publish_impl
>     self.elasticsearch_client.bulk(bulk_actions)
>   File "/root/glp/lib64/python3.6/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
>     return func(*args, params=params, headers=headers, **kwargs)
>   File "/root/glp/lib64/python3.6/site-packages/elasticsearch/client/__init__.py", line 477, in bulk
>     body=body,
>   File "/root/glp/lib64/python3.6/site-packages/elasticsearch/transport.py", line 466, in perform_request
>     raise e
>   File "/root/glp/lib64/python3.6/site-packages/elasticsearch/transport.py", line 434, in perform_request
>     timeout=timeout,
>   File "/root/glp/lib64/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 291, in perform_request
>     self._raise_error(response.status, raw_data)
>   File "/root/glp/lib64/python3.6/site-packages/elasticsearch/connection/base.py", line 329, in _raise_error
>     status_code, error_message, additional_info
> elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: type is missing;2: type is missing;3: type is missing;4: type is missing;5: type is missing;6: type is missing;')
> ```
> 
> 2.I change code databuilder/databuilder/publisher/elasticsearch_publisher.py : 109 index_row = dict(index=dict(_index=self.elasticsearch_new_index,_type=self.elasticsearch_type)) to add _type it is ok

Hello, Currently Databuilder requires ES v7. but I'm facing some issue during ingestion of data. Do you have any clue?
