### ISSUE TITLE
AttributeError: 'ElasticsearchProxyV2' object has no attribute 'fetch_user_search_results'

### ISSUE THREAD

**Issue by saip50** [amundsen-io/amundsen#1933]
Amundsen version: 2.0.0
we aren't able to search any data, click on tags to find data sets as giving exceptions on server side as follows:
-------------------------------------------------------------------------------------------------------------------------
2022-07-19T13:45:20+0000.234 [INFO] _internal._log:225 (1:Thread-30274) - 10.28.150.150 - - [19/Jul/2022 13:45:20] "←[35m←[1mGET /search?query_term=metadata&page_index=0 HTTP/1.1←[0m" 500 -
2022-07-19T13:45:20+0000.241 [ERROR] app.log_exception:1761 (1:Thread-30275) - Exception on /search_user [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flasgger/utils.py", line 273, in wrapper
    return function(*args, **kwargs)
  File "/app/search_service/api/user.py", line 44, in get
    results = self.proxy.fetch_user_search_results(
AttributeError: 'ElasticsearchProxyV2' object has no attribute 'fetch_user_search_results'

**Comment by beauttie** [comment]
Currently running into this bug. What was the resolution to this? I'm running the server locally and am able to curl the health check endpoint but can't seem to search by a query term. I've tried both the `/search` (which returns the same error as above) and the `/v2/search` (returns a 405 with no logs) endpoints.
