### ISSUE TITLE
Bug Report - Amundsen Frontend not building on Mac M3 with Python (3.8.18) and Node (12.22.12)

### ISSUE THREAD

**Issue by mikaalanwar** [amundsen-io/amundsen#2269]
## Expected Behavior
Upon running the following command:
`docker-compose -f docker-amundsen-local.yml up -d amundsenfrontend`

The frontend project should be built successfully.

## Current Behavior
I get the following error log when I run the aforementioned command:

```
$ docker-compose -f docker-amundsen-local.yml up -d amundsenfrontend
WARN[0000] /Users/mikaalanwar/Dev/amundsen/docker-amundsen-local.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Building 190.5s (17/23)                                                                                                                                                  docker:colima
 => [amundsenfrontend internal] load build definition from Dockerfile.frontend.local                                                                                                  0.0s
 => => transferring dockerfile: 885B                                                                                                                                                  0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 4)                                                                                                        0.0s
 => [amundsenfrontend internal] load metadata for docker.io/library/python:3.8-slim                                                                                                   1.4s
 => [amundsenfrontend internal] load metadata for docker.io/library/node:12-slim                                                                                                      1.4s
 => [amundsenfrontend auth] library/python:pull token for registry-1.docker.io                                                                                                        0.0s
 => [amundsenfrontend auth] library/node:pull token for registry-1.docker.io                                                                                                          0.0s
 => [amundsenfrontend internal] load .dockerignore                                                                                                                                    0.0s
 => => transferring context: 126B                                                                                                                                                     0.0s
 => [amundsenfrontend node-stage 1/9] FROM docker.io/library/node:12-slim@sha256:c28ca4124ac84ff1e72ee68abfe70aa4cc86f499c1ef20408dc2d35af1058ac1                                     0.0s
 => [amundsenfrontend internal] load build context                                                                                                                                    3.6s
 => => transferring context: 15.35MB                                                                                                                                                  3.5s
 => [amundsenfrontend stage-1 1/7] FROM docker.io/library/python:3.8-slim@sha256:1d52838af602b4b5a831beb13a0e4d073280665ea7be7f69ce2382f29c5a613f                                     0.0s
 => CACHED [amundsenfrontend stage-1 2/7] WORKDIR /app                                                                                                                                0.0s
 => CACHED [amundsenfrontend stage-1 3/7] COPY ./frontend /app                                                                                                                        0.0s
 => CACHED [amundsenfrontend stage-1 4/7] COPY requirements-dev.txt /app/requirements-dev.txt                                                                                         0.0s
 => CACHED [amundsenfrontend stage-1 5/7] COPY requirements-common.txt /app/requirements-common.txt                                                                                   0.0s
 => CACHED [amundsenfrontend node-stage 2/9] WORKDIR /app/amundsen_application/static                                                                                                 0.0s
 => CACHED [amundsenfrontend node-stage 3/9] COPY ./frontend/amundsen_application/static/package.json /app/amundsen_application/static/package.json                                   0.0s
 => CACHED [amundsenfrontend node-stage 4/9] COPY ./frontend/amundsen_application/static/package-lock.json /app/amundsen_application/static/package-lock.json                         0.0s
 => ERROR [amundsenfrontend node-stage 5/9] RUN npm install                                                                                                                         185.5s
------
 > [amundsenfrontend node-stage 5/9] RUN npm install:
0.281 npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
1.145 npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
1.193 npm WARN deprecated @babel/plugin-proposal-export-namespace-from@7.18.9: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.
1.193 npm WARN deprecated @babel/plugin-proposal-json-strings@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.
1.595 npm WARN deprecated @babel/plugin-proposal-logical-assignment-operators@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
1.720 npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
1.841 npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
1.900 npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
9.688 npm WARN deprecated eslint@7.32.0: This version is no longer supported. Please see https://eslint.org/version-support for other options.
10.98 npm WARN deprecated node-sass@5.0.0: Node Sass is no longer supported. Please use `sass` or `sass-embedded` instead.
14.31 npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
21.99 npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
29.95 npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
46.62 npm WARN deprecated uuid-browser@3.1.0: Package no longer supported and required. Use the uuid package or crypto.randomUUID instead
52.28 npm WARN deprecated @types/history@5.0.0: This is a stub types definition. history provides its own type definitions, so you do not need this installed.
57.11 npm WARN deprecated @humanwhocodes/config-array@0.5.0: Use @eslint/config-array instead
60.74 npm WARN deprecated npmlog@4.1.2: This package is no longer supported.
60.75 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
64.61 npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
81.10 npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
81.24 npm WARN deprecated fstream@1.0.12: This package is no longer supported.
82.84 npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
84.74 npm WARN deprecated @babel/plugin-proposal-private-property-in-object@7.21.11: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-property-in-object instead.
84.91 npm WARN deprecated @babel/plugin-proposal-private-methods@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
85.25 npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
85.69 npm WARN deprecated npmlog@5.0.1: This package is no longer supported.
94.91 npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
96.92 npm WARN deprecated @humanwhocodes/object-schema@1.2.1: Use @eslint/object-schema instead
97.55 npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
99.19 npm WARN deprecated airbnb-prop-types@2.16.0: This package has been renamed to 'prop-types-tools'
101.9 npm WARN deprecated gauge@2.7.4: This package is no longer supported.
102.0 npm WARN deprecated are-we-there-yet@1.1.7: This package is no longer supported.
102.2 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
102.7 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
104.1 npm WARN deprecated json3@3.3.0: Please use the native JSON object instead of JSON 3
105.4 npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
108.6 npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
112.1 npm WARN deprecated highlight.js@9.15.10: Version no longer supported. Upgrade to @latest
117.0 npm WARN deprecated gauge@3.0.2: This package is no longer supported.
117.0 npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported.
126.2 npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
132.7 npm WARN deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported
147.9 npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
148.2 npm WARN deprecated move-concurrently@1.0.1: This package is no longer supported.
148.5 npm WARN deprecated figgy-pudding@3.5.2: This module is no longer supported.
150.0 npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
150.3 npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
150.3 npm WARN deprecated domexception@2.0.1: Use your platform's native DOMException instead
151.5 npm WARN deprecated fsevents@1.2.13: Upgrade to fsevents v2 to mitigate potential security issues
151.8 npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
151.8 npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
151.8 npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
152.6 npm WARN deprecated fs-write-stream-atomic@1.0.10: This package is no longer supported.
152.6 npm WARN deprecated copy-concurrently@1.0.5: This package is no longer supported.
156.7 npm WARN deprecated trim@0.0.1: Use String.prototype.trim() instead
156.8 npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.12.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
182.1
182.1 > husky@4.3.8 install /app/amundsen_application/static/node_modules/husky
182.1 > node husky install
182.1
182.1 husky > Setting up git hooks
182.1 git --version command failed. Got null.
182.1 husky > Failed to install
182.1
182.1 > node-sass@5.0.0 install /app/amundsen_application/static/node_modules/node-sass
182.1 > node scripts/install.js
182.1
182.2 Downloading binary from https://github.com/sass/node-sass/releases/download/v5.0.0/linux-arm64-72_binding.node
183.0 Cannot download "https://github.com/sass/node-sass/releases/download/v5.0.0/linux-arm64-72_binding.node":
183.0
183.0 HTTP error 404 Not Found
183.0
183.0 Hint: If github.com is not accessible in your location
183.0       try setting a proxy via HTTP_PROXY, e.g.
183.0
183.0       export HTTP_PROXY=http://example.com:1234
183.0
183.0 or configure npm proxy via
183.0
183.0       npm config set proxy http://example.com:8080
183.1
183.1 > core-js@2.6.12 postinstall /app/amundsen_application/static/node_modules/@babel/runtime-corejs2/node_modules/core-js
183.1 > node -e "try{require('./postinstall')}catch(e){}"
183.1
183.2 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
183.2
183.2 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
183.2 > https://opencollective.com/core-js
183.2 > https://www.patreon.com/zloirock
183.2
183.2 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
183.2
183.3
183.3 > core-js@2.6.12 postinstall /app/amundsen_application/static/node_modules/babel-runtime/node_modules/core-js
183.3 > node -e "try{require('./postinstall')}catch(e){}"
183.3
183.3 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
183.3
183.3 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
183.3 > https://opencollective.com/core-js
183.3 > https://www.patreon.com/zloirock
183.3
183.3 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
183.3
183.3
183.3 > core-js@3.38.1 postinstall /app/amundsen_application/static/node_modules/core-js
183.3 > node -e "try{require('./postinstall')}catch(e){}"
183.3
183.4 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
183.4
183.4 The project needs your help! Please consider supporting core-js:
183.4 > https://opencollective.com/core-js
183.4 > https://patreon.com/zloirock
183.4 > https://boosty.to/zloirock
183.4 > bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz
183.4
183.4 I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md
183.4
183.4
183.4 > core-js-pure@3.38.1 postinstall /app/amundsen_application/static/node_modules/core-js-pure
183.4 > node -e "try{require('./postinstall')}catch(e){}"
183.4
183.4 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
183.4
183.4 The project needs your help! Please consider supporting core-js:
183.4 > https://opencollective.com/core-js
183.4 > https://patreon.com/zloirock
183.4 > https://boosty.to/zloirock
183.4 > bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz
183.4
183.4 I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md
183.4
183.6
183.6 > core-js@2.6.12 postinstall /app/amundsen_application/static/node_modules/redux-saga-test-plan/node_modules/core-js
183.6 > node -e "try{require('./postinstall')}catch(e){}"
183.6
183.6 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
183.6
183.6 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
183.6 > https://opencollective.com/core-js
183.6 > https://www.patreon.com/zloirock
183.6
183.6 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
183.6
183.8
183.8 > es5-ext@0.10.64 postinstall /app/amundsen_application/static/node_modules/es5-ext
183.8 >  node -e "try{require('./_postinstall')}catch(e){}" || exit 0
183.8
183.9
183.9 > husky@4.3.8 postinstall /app/amundsen_application/static/node_modules/husky
183.9 > opencollective-postinstall || exit 0
183.9
184.0 Thank you for using husky!
184.0 If you rely on this package, please consider supporting our open collective:
184.0 > https://opencollective.com/husky/donate
184.0
184.0
184.0 > node-sass@5.0.0 postinstall /app/amundsen_application/static/node_modules/node-sass
184.0 > node scripts/build.js
184.0
184.0 Building: /usr/local/bin/node /app/amundsen_application/static/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
184.1 gyp info it worked if it ends with ok
184.1 gyp verb cli [
184.1 gyp verb cli   '/usr/local/bin/node',
184.1 gyp verb cli   '/app/amundsen_application/static/node_modules/node-gyp/bin/node-gyp.js',
184.1 gyp verb cli   'rebuild',
184.1 gyp verb cli   '--verbose',
184.1 gyp verb cli   '--libsass_ext=',
184.1 gyp verb cli   '--libsass_cflags=',
184.1 gyp verb cli   '--libsass_ldflags=',
184.1 gyp verb cli   '--libsass_library='
184.1 gyp verb cli ]
184.1 gyp info using node-gyp@7.1.2
184.1 gyp info using node@12.22.12 | linux | arm64
184.1 gyp verb command rebuild []
184.1 gyp verb command clean []
184.1 gyp verb clean removing "build" directory
184.1 gyp verb command configure []
184.1 gyp verb find Python Python is not set from command line or npm configuration
184.1 gyp verb find Python Python is not set from environment variable PYTHON
184.1 gyp verb find Python checking if "python3" can be used
184.1 gyp verb find Python - executing "python3" to get executable path
184.1 gyp verb find Python - "python3" is not in PATH or produced an error
184.1 gyp verb find Python checking if "python" can be used
184.1 gyp verb find Python - executing "python" to get executable path
184.1 gyp verb find Python - "python" is not in PATH or produced an error
184.1 gyp verb find Python checking if "python2" can be used
184.1 gyp verb find Python - executing "python2" to get executable path
184.1 gyp verb find Python - "python2" is not in PATH or produced an error
184.1 gyp ERR! find Python
184.1 gyp ERR! find Python Python is not set from command line or npm configuration
184.1 gyp ERR! find Python Python is not set from environment variable PYTHON
184.1 gyp ERR! find Python checking if "python3" can be used
184.1 gyp ERR! find Python - "python3" is not in PATH or produced an error
184.1 gyp ERR! find Python checking if "python" can be used
184.1 gyp ERR! find Python - "python" is not in PATH or produced an error
184.1 gyp ERR! find Python checking if "python2" can be used
184.1 gyp ERR! find Python - "python2" is not in PATH or produced an error
184.1 gyp ERR! find Python
184.1 gyp ERR! find Python **********************************************************
184.1 gyp ERR! find Python You need to install the latest version of Python.
184.1 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
184.1 gyp ERR! find Python you can try one of the following options:
184.1 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
184.1 gyp ERR! find Python   (accepted by both node-gyp and npm)
184.1 gyp ERR! find Python - Set the environment variable PYTHON
184.1 gyp ERR! find Python - Set the npm configuration variable python:
184.1 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
184.1 gyp ERR! find Python For more information consult the documentation at:
184.1 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
184.1 gyp ERR! find Python **********************************************************
184.1 gyp ERR! find Python
184.1 gyp ERR! configure error
184.1 gyp ERR! stack Error: Could not find any Python installation to use
184.1 gyp ERR! stack     at PythonFinder.fail (/app/amundsen_application/static/node_modules/node-gyp/lib/find-python.js:302:47)
184.1 gyp ERR! stack     at PythonFinder.runChecks (/app/amundsen_application/static/node_modules/node-gyp/lib/find-python.js:136:21)
184.1 gyp ERR! stack     at PythonFinder.<anonymous> (/app/amundsen_application/static/node_modules/node-gyp/lib/find-python.js:179:16)
184.1 gyp ERR! stack     at PythonFinder.execFileCallback (/app/amundsen_application/static/node_modules/node-gyp/lib/find-python.js:266:16)
184.1 gyp ERR! stack     at exithandler (child_process.js:315:5)
184.1 gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
184.1 gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
184.1 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
184.1 gyp ERR! stack     at onErrorNT (internal/child_process.js:470:16)
184.1 gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
184.1 gyp ERR! System Linux 6.8.0-39-generic
184.1 gyp ERR! command "/usr/local/bin/node" "/app/amundsen_application/static/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
184.1 gyp ERR! cwd /app/amundsen_application/static/node_modules/node-sass
184.1 gyp ERR! node -v v12.22.12
184.1 gyp ERR! node-gyp -v v7.1.2
184.1 gyp ERR! not ok
184.1 Build failed with error code: 1
184.6 npm WARN notsup Unsupported engine for @rehooks/local-storage@2.4.5: wanted: {"node":">=18.0.0"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: @rehooks/local-storage@2.4.5
184.6 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@* (node_modules/fsevents):
184.6 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
184.6 npm WARN notsup Unsupported engine for react-avatar@2.5.1: wanted: {"node":"8.x.x"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: react-avatar@2.5.1
184.6 npm WARN notsup Unsupported engine for type-fest@4.26.1: wanted: {"node":">=16"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: type-fest@4.26.1
184.6 npm WARN notsup Unsupported engine for stylelint@15.11.0: wanted: {"node":"^14.13.1 || >=16.0.0"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: stylelint@15.11.0
184.6 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
184.6 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
184.6 npm WARN notsup Unsupported engine for cheerio@1.0.0: wanted: {"node":">=18.17"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: cheerio@1.0.0
184.6 npm WARN notsup Unsupported engine for undici@6.20.0: wanted: {"node":">=18.17"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: undici@6.20.0
184.6 npm WARN notsup Unsupported engine for whatwg-mimetype@4.0.0: wanted: {"node":">=18"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: whatwg-mimetype@4.0.0
184.6 npm WARN notsup Unsupported engine for whatwg-encoding@3.1.1: wanted: {"node":">=18"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: whatwg-encoding@3.1.1
184.6 npm WARN notsup Unsupported engine for cosmiconfig@8.3.6: wanted: {"node":">=14"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: cosmiconfig@8.3.6
184.6 npm WARN notsup Unsupported engine for write-file-atomic@5.0.1: wanted: {"node":"^14.17.0 || ^16.13.0 || >=18.0.0"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: write-file-atomic@5.0.1
184.6 npm WARN notsup Unsupported engine for supports-hyperlinks@3.1.0: wanted: {"node":">=14.18"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: supports-hyperlinks@3.1.0
184.6 npm WARN notsup Unsupported engine for @csstools/css-tokenizer@2.4.1: wanted: {"node":"^14 || ^16 || >=18"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: @csstools/css-tokenizer@2.4.1
184.6 npm WARN notsup Unsupported engine for @csstools/selector-specificity@3.1.1: wanted: {"node":"^14 || ^16 || >=18"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: @csstools/selector-specificity@3.1.1
184.6 npm WARN notsup Unsupported engine for @csstools/css-parser-algorithms@2.7.1: wanted: {"node":"^14 || ^16 || >=18"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: @csstools/css-parser-algorithms@2.7.1
184.6 npm WARN notsup Unsupported engine for @csstools/media-query-list-parser@2.1.13: wanted: {"node":"^14 || ^16 || >=18"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: @csstools/media-query-list-parser@2.1.13
184.6 npm WARN notsup Unsupported engine for signal-exit@4.1.0: wanted: {"node":">=14"} (current: {"node":"12.22.12","npm":"6.14.16"})
184.6 npm WARN notsup Not compatible with your version of node/npm: signal-exit@4.1.0
184.6 npm WARN react-sanitized-html@2.0.0 requires a peer of sanitize-html@^1.16.1 but none is installed. You must install peer dependencies yourself.
184.6 npm WARN analytics-utils@1.0.12 requires a peer of @types/dlv@^1.0.0 but none is installed. You must install peer dependencies yourself.
184.7 npm WARN stylelint-scss@3.21.0 requires a peer of stylelint@^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 but none is installed. You must install peer dependencies yourself.
184.7 npm WARN webpack-filter-warnings-plugin@1.2.1 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
184.7 npm WARN @webpack-contrib/schema-utils@1.0.0-beta.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
184.7
184.7 npm ERR! code ELIFECYCLE
184.7 npm ERR! errno 1
184.7 npm ERR! node-sass@5.0.0 postinstall: `node scripts/build.js`
184.7 npm ERR! Exit status 1
184.7 npm ERR!
184.7 npm ERR! Failed at the node-sass@5.0.0 postinstall script.
184.7 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
184.7
184.7 npm ERR! A complete log of this run can be found in:
184.7 npm ERR!     /root/.npm/_logs/2024-10-12T22_27_09_036Z-debug.log
------
failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1
```

## Possible Solution
The build process should be tested and fixed on Apple M3 machines and dependencies / docs need to be updated accordingly.

## Steps to Reproduce
Simply run the docker-compose build command.

## Screenshots (if appropriate)
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/15c28a31-372e-4413-a28e-b1f0cef84ced">

## Context
Unable to build it locally and test certain use cases.

## Your Environment
* Amunsen version used: f6949e79 (latest - main)
* Data warehouse stores: N/A
* Deployment (k8s or native): local
* Link to your fork or repository: N/A (using a directly cloned version)

**Comment by unfixa1** [comment]
Node 12.x is outdated. It is recommended to upgrade to the latest LTS version (such as 16.x or 18.x) to avoid incompatibility issues with dependencies.
You can use [servbay](servbay.com) to deploy different versions of node.js at the same time and switch the required development environment with one click
