### ISSUE TITLE
Improve Databuilder ergonomics 

### ISSUE THREAD

**Issue by jornh** [amundsen-io/amundsen#371]
Databuilder is, in some cases, hard to figure out to how to initialize/configure with pretty verbose syntax leading to much boilerplate being duplicated. Some error messages are not very helpful and even though there is plenty of reference documentation we should have better “guard rails”.

Examples of not very helpful error traces:

* https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1564478013214900

* https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1586443111323500?thread_ts=1586439037.322700&channel=CGFBVT23V&message_ts=1586443111.323500

```

 Hi ! I am trying to extract my own data from hive . I have used hive_table_metadata_extractor to extract data from hive. Please find attached the sample code that i am trying to run. I am trying to extract only one table from hive and publish it in neo4j. I am able to create table in hive but not able to publish in neo4j. But i am facing the below issue - Traceback (most recent call last):
 File "example/scripts/sample_data_loader.py", line 216, in &lt;module&gt;
  job1.launch()
 File "/mnt/tmp/lyft/amundsendatabuilder/venv/lib64/python3.6/dist-packages/amundsen_databuilder-1.4.0-py3.6.egg/databuilder/job/job.py", line 78, in launch
 File "/mnt/tmp/lyft/amundsendatabuilder/venv/lib64/python3.6/dist-packages/amundsen_databuilder-1.4.0-py3.6.egg/databuilder/job/job.py", line 66, in launch
 File "/mnt/tmp/lyft/amundsendatabuilder/venv/lib64/python3.6/dist-packages/amundsen_databuilder-1.4.0-py3.6.egg/databuilder/job/job.py", line 52, in _init
 File "/mnt/tmp/lyft/amundsendatabuilder/venv/lib64/python3.6/dist-packages/amundsen_databuilder-1.4.0-py3.6.egg/databuilder/task/task.py", line 46, in init
TypeError: get_scope() missing 1 required positional argument: 'self'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
 File "/mnt/tmp/lyft/amundsendatabuilder/venv/lib64/python3.6/dist-packages/amundsen_databuilder-1.4.0-py3.6.egg/databuilder/utils/closer.py", line 48, in close
TypeError: close() missing 1 required positional argument: 'self'

**Comment by rsyi** [comment]
I totally agree with this! I feel like a lot of the examples in `example/scripts` are cumbersome because of the way `ConfigTree` keys are templated by the extractor class attributes. Maybe this is best practice, but it makes the whole thing pretty hard to read.

Perhaps a first step (to help beginners) could be just modifying the sample scripts to have explicit key declarations? E.g. the following:

```
job_config = ConfigFactory.from_dict({
    'extractor.csv.file_location': file_loc
})
```

is a lot easier for me to grok than:
```
job_config = ConfigFactory.from_dict({
    'extractor.csv.{}'.format(CsvExtractor.FILE_LOCATION): file_loc
})
```

when there are 15 of these, it makes it a little difficult to understand what's going on. I'd be happy to make these change -- let me know. :)

**Comment by feng-tao** [comment]
yeah, I think it makes sense to simplify like this. @rsyi , if you have time, I am +1 on that. Thanks a lot!

**Comment by jornh** [comment]
With https://github.com/amundsen-io/amundsendatabuilder/pull/265 merged (long time ago) let’s close this.

Thanks @rsyi!
