### ISSUE TITLE
Invalid input exception in NODE_MERGE_TEMPLATE of neo4j_csv_publisher

### ISSUE THREAD

**Issue by ayush-san** [amundsen-io/amundsen#640]
While creating users using User model class, I received the following error for one of the users in our org.

```
ERROR - Failed to execute Cypher query
 Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/databuilder/publisher/neo4j_csv_publisher.py", line 449, in _execute_statement
    tx.commit()
  File "/usr/local/lib/python3.7/site-packages/neo4j/__init__.py", line 792, in commit
    self.close()
  File "/usr/local/lib/python3.7/site-packages/neo4j/__init__.py", line 815, in close
    self.sync()
  File "/usr/local/lib/python3.7/site-packages/neo4j/__init__.py", line 780, in sync
    self.session.sync()
  File "/usr/local/lib/python3.7/site-packages/neo4j/__init__.py", line 531, in sync
    detail_count, _ = self._connection.sync()
  File "/usr/local/lib/python3.7/site-packages/neobolt/direct.py", line 527, in sync
    detail_delta, summary_delta = self.fetch()
  File "/usr/local/lib/python3.7/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/usr/local/lib/python3.7/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.7/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherSyntaxError: Invalid input 'i': expected 't/T' (line 1, column 36 (offset: 35))
"MERGE (node:User {key: 'some.d'name@org.com'})"
```

In [neo4j_csv_publisher.py](https://github.com/amundsen-io/amundsendatabuilder/blob/master/databuilder/publisher/neo4j_csv_publisher.py#L103), we have defined node merge template as 

```
NODE_MERGE_TEMPLATE = Template("""MERGE (node:$LABEL {key: '${KEY}'})
ON CREATE SET ${create_prop_body}
${update_statement}""")
```

## Current Behavior
Due to `'` in the email id of the user and use of `'` for encoding in `NODE_MERGE_TEMPLATE`, I am getting invalid input exception 

## Your Environment
* AmunsenDataBuilder version used: 2.6.5
* Data warehouse stores: neo4j
* Deployment (k8s or native): ECS

**Comment by dorianj** [comment]
Root cause: https://github.com/amundsen-io/amundsen/issues/513

I think here, escaping `KEY` would suffice -- can you try escaping it on input as a work-around?

**Comment by ayush-san** [comment]
@dorianj I can escape it in my input but will it be escaped during [auth_user](https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/amundsen_application/api/v0.py#L23) call?
