### ISSUE TITLE
Bug Report: Neo4j key values with an apostrophe ` cause syntax errors in publishing

### ISSUE THREAD

**Issue by instazackwu** [amundsen-io/amundsen#685]
Special characters in the constructed neo4j cypher code in 
https://github.com/amundsen-io/amundsendatabuilder/blob/HEAD/databuilder/publisher/neo4j_csv_publisher.py#L103-#L105 and 
https://github.com/amundsen-io/amundsendatabuilder/blob/HEAD/databuilder/publisher/neo4j_csv_publisher.py#L109-#L112

causes `neobolt.exceptions.CypherSyntaxError`

## Expected Behavior

The key value with an `'` should be accepted

## Current Behavior

The key value with a `'` causes 

`neobolt.exceptions.CypherSyntaxError: Invalid input ' ': expected 't/T' (line 1, column 80 (offset: 79))
"MERGE (node:Column {key: 'snowflake://SAMPLE_DB.SAMPLE_SCHEMA/SAMPLE_TABLE/sample's_table})"`

## Possible Solution

1. Parameterize `*_TEMPLATE` strings in https://github.com/amundsen-io/amundsendatabuilder/blob/HEAD/databuilder/publisher/neo4j_csv_publisher.py 
2. A possibly more universal solution - escape both ' and \ characters with a leading \ character as per https://stackoverflow.com/questions/30513601/neo4j-how-to-handle-special-characters-like-in-cypher-statements (Thanks to Jorn Hansen )

## Steps to Reproduce

1. Add the following line to https://github.com/amundsen-io/amundsendatabuilder/blob/master/example/sample_data/sample_table.csv:
`hive,gold,test_schema,"test's_table4","4th test","needs_documentation",false,`
2. Run the sample installation (https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md)
3. See the error
```
$ python3 example/scripts/sample_data_loader.py

ERROR:databuilder.publisher.neo4j_csv_publisher:Failed to publish. Rolling back.
Traceback (most recent call last):
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/amundsen_databuilder-3.2.0-py3.7.egg/databuilder/publisher/neo4j_csv_publisher.py", line 212, in publish_impl
    tx.commit()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 792, in commit
    self.close()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 815, in close
    self.sync()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 780, in sync
    self.session.sync()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 531, in sync
    detail_count, _ = self._connection.sync()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neobolt/direct.py", line 527, in sync
    detail_delta, summary_delta = self.fetch()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherSyntaxError: Invalid input '_': expected 't/T' (line 1, column 62 (offset: 61))
"MERGE (node:Description {key: 'hive://gold.test_schema/test's_table4/_description'})"
                                                              ^
Traceback (most recent call last):
  File "example/scripts/sample_data_loader.py", line 283, in <module>
    run_table_column_job('example/sample_data/sample_table.csv', 'example/sample_data/sample_col.csv')
  File "example/scripts/sample_data_loader.py", line 144, in run_table_column_job
    job.launch()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/amundsen_databuilder-3.2.0-py3.7.egg/databuilder/job/job.py", line 77, in launch
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/amundsen_databuilder-3.2.0-py3.7.egg/databuilder/job/job.py", line 73, in launch
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/amundsen_databuilder-3.2.0-py3.7.egg/databuilder/publisher/base_publisher.py", line 40, in publish
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/amundsen_databuilder-3.2.0-py3.7.egg/databuilder/publisher/base_publisher.py", line 37, in publish
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/amundsen_databuilder-3.2.0-py3.7.egg/databuilder/publisher/neo4j_csv_publisher.py", line 221, in publish_impl
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/amundsen_databuilder-3.2.0-py3.7.egg/databuilder/publisher/neo4j_csv_publisher.py", line 212, in publish_impl
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 792, in commit
    self.close()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 815, in close
    self.sync()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 780, in sync
    self.session.sync()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neo4j/__init__.py", line 531, in sync
    detail_count, _ = self._connection.sync()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neobolt/direct.py", line 527, in sync
    detail_delta, summary_delta = self.fetch()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherSyntaxError: Invalid input '_': expected 't/T' (line 1, column 62 (offset: 61))
"MERGE (node:Description {key: 'hive://gold.test_schema/test's_table4/_description'})"
                                                              ^
```

## Context

When running data builder for tables with special characters (`'`) in them, publishing fails and we can't index these tables in Amundsen. 

## Your Environment

* Amunsen version used: `3.2.0`
* Data warehouse stores: Snowflake
* Deployment (k8s or native): Not sure about this.
* Link to your fork or repository: https://github.com/instazackwu/amundsendatabuilder

**Comment by instazackwu** [comment]
https://github.com/amundsen-io/amundsen/issues/513 seems to be the first suggested solution.

Thanks for the suggestion to open this issue first @jornh - 

cc @Alagappan this was another small issue with Snowflake table names.

**Comment by feng-tao** [comment]
@Alagappan @instazackwu do you get it resolved?

**Comment by instazackwu** [comment]
This is still an issue - the steps to reproduce should still give that same error. I was waiting to see if https://github.com/amundsen-io/amundsen/issues/513 had any movement before trying to implement something. 

For now, we are just ignoring any table names that have a `'` in them to bypass this issue

**Comment by higee** [comment]
Columns with backslash ('\\') also raises CypherSyntax error. Let me know if I need to open a new case.

```
Failed to execute Cypher query\n'
Traceback (most recent call last):\n'
  File "/pyroot/lib/python3.8/site-packages/databuilder/publisher/neo4j_csv_publisher.py", line 432, in _execute_statement\n'
    tx.commit()\n'
  File "/pyroot/lib/python3.8/site-packages/neo4j/__init__.py", line 809, in commit\n'
    self.close()\n'
  File "/pyroot/lib/python3.8/site-packages/neo4j/__init__.py", line 832, in close\n'
    self.sync()\n'
  File "/pyroot/lib/python3.8/site-packages/neo4j/__init__.py", line 797, in sync\n'
    self.session.sync()\n'
  File "/pyroot/lib/python3.8/site-packages/neo4j/__init__.py", line 542, in sync\n'
    detail_count, _ = self._connection.sync()\n'
  File "/pyroot/lib/python3.8/site-packages/neobolt/direct.py", line 527, in sync\n'
    detail_delta, summary_delta = self.fetch()\n'
  File "/pyroot/lib/python3.8/site-packages/neobolt/direct.py", line 419, in fetch\n'
    return self._fetch()\n'
  File "/pyroot/lib/python3.8/site-packages/neobolt/direct.py", line 461, in _fetch\n'
    response.on_failure(summary_metadata or {})\n'
  File "/pyroot/lib/python3.8/site-packages/neobolt/direct.py", line 755, in on_failure\n'
    raise CypherError.hydrate(**metadata)\n'
neobolt.exceptions.CypherSyntaxError: Invalid input \'p\': expected whitespace, \'.\', node labels, \'[\', "=~", IN, STARTS, ENDS, CONTAINS, IS, \'^\', \'*\', \'/\', \'%\', \'+\', \'-\', \'=\', "<>", "!=", \'<\', \'>\', "<=", ">=", AND, XOR, OR, \',\' or \'}\' (line 2, column 28 (offset: 127))\n'
"ON CREATE SET node.name = \'properties.ad_name\\\\\', node.type = \'string\', node.sort_order = 85, node.published_tag = \'2020-09-30\', node.publisher_last_updated_epoch_ms = timestamp()"\n'
```

raw column is `properties.ad_name\`

**Comment by jornh** [comment]
@higee that doesn't surprise me - as `\` is the escape character in possible solution number 2. ☝️  so both problems are closely related and should be handled by the same PR.

> ## Possible Solution
> 1. Parameterize `*_TEMPLATE` strings in https://github.com/amundsen-io/amundsendatabuilder/blob/HEAD/databuilder/publisher/neo4j_csv_publisher.py
> 2. A possibly more universal solution - escape both ' and \ characters with a leading \ character as per https://stackoverflow.com/questions/30513601/neo4j-how-to-handle-special-characters-like-in-cypher-statements (Thanks to Jorn Hansen )

**Comment by feng-tao** [comment]
https://github.com/amundsen-io/amundsendatabuilder/pull/382 is now merged

**Comment by jornh** [comment]
@instazackwu after merge of https://github.com/amundsen-io/amundsendatabuilder/pull/382 any outstanding points before you can close this issue?

**Comment by instazackwu** [comment]
Oh great, confirmed https://github.com/amundsen-io/amundsendatabuilder/pull/382 fixes this! Appreciate the conclusion of this issue :), thank you everyone!
