### ISSUE TITLE
Amundsen Atlas search not working

### ISSUE THREAD

**Issue by chrigui94** [amundsen-io/amundsen#737]
hi everyone, i am trying to set up amundsen (search-library) with Atlas backend and the following configs (witout host, user and password):

```
PROXY_ENDPOINT = 'localhost:21443'
PROXY_CLIENT_KEY = os.environ.get('PROXY_CLIENT_KEY')
PROXY_CLIENT = PROXY_CLIENTS['ATLAS']
```
Normally it returns the searched entities existing in Atlas but it doesn't work

I get this error
```
2020-09-28T14:29:47+0200.195 [ERROR] v0._search_table:113 (181323:Thread-3) - Encountered exception: HTTPConnectionPool(host='0.0.0.0', port=5001): Read timed out. (read timeout=3)
Traceback (most recent call last):
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='0.0.0.0', port=5001): Read timed out. (read timeout=3)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/amundsen_frontend-2.3.0-py3.7.egg/amundsen_application/api/search/v0.py", line 95, in _search_table
    response = request_search(url=url)
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/amundsen_frontend-2.3.0-py3.7.egg/amundsen_application/api/utils/request_utils.py", line 78, in request_search
    data=data)
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/amundsen_frontend-2.3.0-py3.7.egg/amundsen_application/api/utils/request_utils.py", line 112, in request_wrapper
    return s.get(url, headers=headers, timeout=timeout_sec)
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/opt/apps/anaconda3/envs/amundsen-frontend/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='0.0.0.0', port=5001): Read timed out. (read timeout=3)
```

* Amunsen version used: the last version
* Data warehouse stores: Atlas version 2.4.0
* Deployment (k8s or native):  k8s

**Comment by dorianj** [comment]
@chrigui94 were you able to figure this out? Please re-open if you're still seeing it.
