### ISSUE TITLE
Bookmarks are not working after kickstart

### ISSUE THREAD

**Issue by ben-j-herbertz** [amundsen-io/amundsen#740]
Amundsen has been installed locally based on the latest version 2.4 and built from source.
Atlas is used as backend and search engine.

Note: Atlas was installed and used before. I used the kickstart method to generate all types.

## Expected Behavior

Bookmarks can be used.

## Current Behavior

Bookmarks are not working

Error from metadata service:
```
2020-09-28T14:30:06+0200.000 [ERROR] base.__getattr__:488 (181133:Thread-18) - Missing attr EntityUniqueAttribute: searchParameters
2020-09-28T14:30:03+0200.226 [ERROR] atlas_proxy._get_bookmark_entity:282 (181133:Thread-13) - Bookmark not found. 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/proxy/atlas_proxy.py", line 275, in _get_bookmark_entity
    user_entity.entity[self.GUID_KEY], bookmark_qn, entity_uri)
TypeError: 'NoneType' object is not subscriptable
2020-09-28T14:30:03+0200.227 [ERROR] user.put:121 (181133:Thread-13) - UserFollowAPI PUT Failed
Traceback (most recent call last):
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/proxy/atlas_proxy.py", line 275, in _get_bookmark_entity
    user_entity.entity[self.GUID_KEY], bookmark_qn, entity_uri)
TypeError: 'NoneType' object is not subscriptable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/api/user.py", line 114, in put
    resource_type=to_resource_type(label=resource_type))
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/proxy/atlas_proxy.py", line 887, in add_resource_relation_by_user
    entity = self._get_bookmark_entity(entity_uri=id, user_id=user_id)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/proxy/atlas_proxy.py", line 284, in _get_bookmark_entity
    .format(bookmark_qn=bookmark_qn))
metadata_service.exception.NotFoundException: Bookmark( <HIVE_TABLE> ) does not exist
```

Error from frontend service:
```
2020-09-28T14:30:08+0200.710 [INFO] _internal._log:122 (181323:Thread-28) - 140.34.40.241 - - [28/Sep/2020 14:30:08] "PUT /api/metadata/v0/user/bookmark HTTP/1.1" 500 -
```

## Possible Solution
/

## Steps to Reproduce
/

## Screenshots (if appropriate)
/

## Context
/
## Your Environment
versions:
- amundsen-search: 2.4.0
- amundsen-metadata: 2.5.5
- amundsen-frontend: 2.3.0
- amundsen-databuilder: 3.3.2

Data warehouse stores: hive metastore HDP 3.1.0.3.1.5 on mariadb
Deployment (k8s or native): native

**Comment by feng-tao** [comment]
cc @verdan @mgorsk1

**Comment by verdan** [comment]
@pPanda-beta can you please confirm if you have the user `palash.das@rapido.bike` in your Atlas? 
It seems like the user entity is not available in Atlas in your case.

**Comment by pPanda-beta** [comment]
@verdan 
Yes it was not there. You were right about it.  

### Wrong assumption from my side: 
I thought amundsen metadata will create the user if not found, similar to what it does when we set the owner of the table.

### Next problem :
This regex is not correct. 
https://github.com/amundsen-io/amundsenmetadatalibrary/blob/3c9a55e6af4cac9b342803c34cfe81851470e7f5/metadata_service/proxy/atlas_proxy.py#L156-L178

Error log
```
amundsen-metadata-57796dd865-ktzxm metadata 2020-10-15T09:17:42+0000.537 [ERROR] user.get:88 (14:Thread-213) - UserFollowAPI GET Failed
amundsen-metadata-57796dd865-ktzxm metadata Traceback (most recent call last):
amundsen-metadata-57796dd865-ktzxm metadata   File "/usr/local/lib/python3.7/site-packages/metadata_service/api/user.py", line 64, in get
amundsen-metadata-57796dd865-ktzxm metadata     relation_type=UserResourceRel.follow)
amundsen-metadata-57796dd865-ktzxm metadata   File "/usr/local/lib/python3.7/site-packages/metadata_service/proxy/atlas_proxy.py", line 924, in get_table_by_user_relation
amundsen-metadata-57796dd865-ktzxm metadata     resource_type=ResourceType.Table.name)
amundsen-metadata-57796dd865-ktzxm metadata   File "/usr/local/lib/python3.7/site-packages/metadata_service/proxy/atlas_proxy.py", line 852, in _get_resources_followed_by_user
amundsen-metadata-57796dd865-ktzxm metadata     cluster=res['cluster'],
amundsen-metadata-57796dd865-ktzxm metadata KeyError: 'cluster'
```

### Sample bookmark qn to reproduce : 
```
apps.af_cr_test1.hive_table.palash.das@rapido.bike.bookmark@primary
```

![image](https://user-images.githubusercontent.com/20648934/96108707-896af380-0efb-11eb-8470-88b800248293.png)

**Comment by pPanda-beta** [comment]
@mgorsk1 
I think it got introduced in this commit
https://github.com/amundsen-io/amundsenmetadatalibrary/commit/e8735273ffd8bb2def3a167f28fb8661a0f71287

**Comment by pPanda-beta** [comment]
Raised a PR https://github.com/amundsen-io/amundsenmetadatalibrary/pull/216
