### ISSUE TITLE
HBase Tables are not working after kickstart

### ISSUE THREAD

**Issue by ben-j-herbertz** [amundsen-io/amundsen#741]
Amundsen has been installed locally based on the latest version 2.4 and built from source.
Atlas is used as backend and search engine.

Note: Atlas was installed and used before. I used the kickstart method to generate all types.

## Expected Behavior

HBase tables can be displayed.

## Current Behavior

HBase tables can not be displayed.

Error from metadata service:
```
22020-09-28T14:29:58+0200.600 [INFO] _internal._log:122 (181133:Thread-10) - 127.0.0.1 - - [28/Sep/2020 14:29:58] "GET /table/hbase_table://<HBASE_TABLE> HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flasgger/utils.py", line 249, in wrapper
    return function(*args, **kwargs)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/api/table.py", line 33, in get
    table = self.client.get_table(table_uri=table_uri)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/proxy/atlas_proxy.py", line 433, in get_table
    programmatic_descriptions = self._get_programmatic_descriptions(attrs.get('parameters', dict()))
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/proxy/atlas_proxy.py", line 964, in _get_programmatic_descriptions
    for source, text in parameters.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

Error from frontend service:
```
2020-09-28T14:30:09+0200.211 [DEBUG] connectionpool._make_request:396 (181323:Thread-29) - http://0.0.0.0:5002 "GET <HBASE_TABLE> HTTP/1.1" 500 None
2020-09-28T14:30:09+0200.212 [ERROR] v0._get_table_metadata:134 (181323:Thread-29) - Encountered error: Metadata request failed
```

## Possible Solution
/

## Steps to Reproduce
/

## Screenshots (if appropriate)
/

## Context
/
## Your Environment
versions:
- amundsen-search: 2.4.0
- amundsen-metadata: 2.5.5
- amundsen-frontend: 2.3.0
- amundsen-databuilder: 3.3.2

Data warehouse stores: hive metastore HDP 3.1.0.3.1.5 on mariadb
Deployment (k8s or native): native

**Comment by feng-tao** [comment]
cc @verdan @mgorsk1
