### ISSUE TITLE
Search functionality don't work as expected 

### ISSUE THREAD

**Issue by chrigui94** [amundsen-io/amundsen#752]
2020-10-08T13:55:11+0200.976 [INFO] _internal._log:122 (45004:Thread-49) - 127.0.0.1 - - [08/Oct/2020 13:55:11] "GET /table/hive_table://hdptuc01.default/test1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/flasgger/utils.py", line 249, in wrapper
    return function(*args, **kwargs)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/api/table.py", line 33, in get
    table = self.client.get_table(table_uri=table_uri)
  File "/opt/apps/anaconda3/envs/amundsen-metadata/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/proxy/atlas_proxy.py", line 431, in get_table
    attrs = table_details[self.ATTRS_KEY]
TypeError: 'NoneType' object is not subscriptable
2020-10-08T13:58:26+0200.626 [DEBUG] base.__init__:430 (45004:Thread-50) - Generating new model class: EntityUniqueAttribute with the data: {'typeName': 'hive_table'}
2020-10-08T13:58:26+0200.626 [DEBUG] base.__getattr__:484 (45004:Thread-50) - Lazy-loading the relationship attribute: 'entity'.
2020-10-08T13:58:26+0200.626 [ERROR] base.__getattr__:488 (45004:Thread-50) - Missing attr EntityUniqueAttribute: searchParameters

## Your Environment

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by Golodhros** [comment]
Could you add more information on this ticket?
When did this happen, what were. you trying to do, etc.

**Comment by dorianj** [comment]
Please re-open if you get a chance to add the repro case or at least some more context
