### ISSUE TITLE
Bug Report: quick start has error when access test_table1

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#784]
I encountered the follow error when following the quick https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#bootstrap-a-default-version-of-amundsen-using-docker:
```
amundsenfrontend    | 2020-10-28T06:32:46+0000.717 [DEBUG] connectionpool._make_request:393 (8:MainThread) - http://amundsenmetadata:5000 "GET /table/hive://gold.test_schema/test_table1 HTTP/1.1" 200 4596
amundsenfrontend    | 2020-10-28T06:32:46+0000.724 [ERROR] v0._get_table_metadata:135 (8:MainThread) - Encountered exception:
amundsenfrontend    | Traceback (most recent call last):
amundsenfrontend    |   File "/app/amundsen_application/api/metadata/v0.py", line 129, in _get_table_metadata
amundsenfrontend    |     results_dict['tableData'] = marshall_table_full(table_data_raw)
amundsenfrontend    |   File "/app/amundsen_application/api/utils/metadata_utils.py", line 67, in marshall_table_full
amundsenfrontend    |     results['partition'] = _get_partition_data(results['watermarks'])
amundsenfrontend    |   File "/app/amundsen_application/api/utils/metadata_utils.py", line 104, in _get_partition_data
amundsenfrontend    |     high_watermark = next(filter(lambda x: x['watermark_type'] == 'high_watermark', watermarks))
amundsenfrontend    | StopIteration
```

Reproduced:
Follow https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#bootstrap-a-default-version-of-amundsen-using-docker

**Comment by allisonsuarez** [comment]
fixed on PR above
