### ISSUE TITLE
Unable to use the Sample Data

### ISSUE THREAD

**Issue by relvan1** [amundsen-io/amundsen#786]
Hey,

I am unable to use the sample dataset with the Neo4j as backend and tried to load the sample data using the following command,
$ sudo python example/scripts/sample_data_loader.py

Error:
ERROR:databuilder.publisher.neo4j_csv_publisher:Failed to publish. Rolling back.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/databuilder/publisher/neo4j_csv_publisher.py", line 212, in publish_impl
    tx.commit()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neo4j/__init__.py", line 809, in commit
    self.close()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neo4j/__init__.py", line 832, in close
    self.sync()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neo4j/__init__.py", line 797, in sync
    self.session.sync()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neo4j/__init__.py", line 542, in sync
    detail_count, _ = self._connection.sync()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neobolt/direct.py", line 527, in sync
    detail_delta, summary_delta = self.fetch()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherSyntaxError: Invalid input '_': expected 't/T' (line 1, column 56 (offset: 55))
"MERGE (node:Table {key: 'hive://gold.test_schema/test's_table4'})"
                                                        ^
Traceback (most recent call last):
  File "example/scripts/sam.py", line 261, in <module>
    run_table_column_job('example/sample_data/sample_table.csv', 'example/sample_data/sample_col.csv')
  File "example/scripts/sam.py", line 122, in run_table_column_job
    job.launch()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/databuilder/job/job.py", line 77, in launch
    raise e
  File "/home/ubuntu/.local/lib/python3.7/site-packages/databuilder/job/job.py", line 73, in launch
    self.publisher.publish()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/databuilder/publisher/base_publisher.py", line 40, in publish
    raise e
  File "/home/ubuntu/.local/lib/python3.7/site-packages/databuilder/publisher/base_publisher.py", line 37, in publish
    self.publish_impl()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/databuilder/publisher/neo4j_csv_publisher.py", line 221, in publish_impl
    raise e
  File "/home/ubuntu/.local/lib/python3.7/site-packages/databuilder/publisher/neo4j_csv_publisher.py", line 212, in publish_impl
    tx.commit()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neo4j/__init__.py", line 809, in commit
    self.close()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neo4j/__init__.py", line 832, in close
    self.sync()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neo4j/__init__.py", line 797, in sync
    self.session.sync()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neo4j/__init__.py", line 542, in sync
    detail_count, _ = self._connection.sync()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neobolt/direct.py", line 527, in sync
    detail_delta, summary_delta = self.fetch()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/home/ubuntu/.local/lib/python3.7/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherSyntaxError: Invalid input '_': expected 't/T' (line 1, column 56 (offset: 55))
"MERGE (node:Table {key: 'hive://gold.test_schema/test's_table4'})"
                                                        ^

**Comment by jornh** [comment]
Try updating your site-packages with the below - or whatever you did in your environmennt to reinstall requirements.txt and re-run setup.py:

```
 $ python3 -m venv venv
 $ source venv/bin/activate  
 $ pip3 install -r requirements.txt
 $ python3 setup.py install
 $ python3 example/scripts/sample_data_loader.py
```

**Comment by relvan1** [comment]
@jornh Its working now Thanks. But I couldn't see any Datasets, Am I missing anything.

**Comment by jornh** [comment]
I can't say. Only help I can offer is to check the troubleshooting section in the Quickstart guide.

**Comment by relvan1** [comment]
ok. Thanks a lot @jornh

**Comment by jornh** [comment]
@relvan1 with your initial issue solved please close this issue so we can keep it neat and tidy in here.
