### ISSUE TITLE
Running sample_data_loader.py raises a ValueError

### ISSUE THREAD

**Issue by HenryLiMN** [amundsen-io/amundsen#803]
## Expected Behavior

I'm following the quick start guide: https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#bootstrap-a-default-version-of-amundsen-using-docker

Everything up to the sample data ingestion step works. The expected behavior is that the sample table metadata is ingested into the Neo4j graph.

## Current Behavior

When I get to the step where it's supposed to ingest sample data using `python3 example/scripts/sample_data_loader.py
`, it raises a ValueError and fails to ingest the sample data:

```
(venv) heli@Hes-MacBook-Pro amundsendatabuilder % python3 example/scripts/sample_data_loader.py
Traceback (most recent call last):
  File "example/scripts/sample_data_loader.py", line 285, in <module>
    'databuilder.models.table_stats.TableColumnStats')
  File "example/scripts/sample_data_loader.py", line 115, in run_csv_job
    publisher=Neo4jCsvPublisher()).launch()
  File "/Users/heli/Projects/amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/amundsen_databuilder-4.0.3-py3.7.egg/databuilder/job/job.py", line 77, in launch
  File "/Users/heli/Projects/amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/amundsen_databuilder-4.0.3-py3.7.egg/databuilder/job/job.py", line 67, in launch
  File "/Users/heli/Projects/amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/amundsen_databuilder-4.0.3-py3.7.egg/databuilder/task/task.py", line 65, in run
  File "/Users/heli/Projects/amundsen/amundsendatabuilder/venv/lib/python3.7/site-packages/amundsen_databuilder-4.0.3-py3.7.egg/databuilder/loader/file_system_neo4j_csv_loader.py", line 119, in load
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/csv.py", line 151, in _dict_to_list
    + ", ".join([repr(x) for x in wrong_fields]))
ValueError: dict contains fields not in fieldnames: 'stat_val'
```

## Steps to Reproduce

1. Follow the steps in https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#bootstrap-a-default-version-of-amundsen-using-docker
2. Get to the `python3 example/scripts/sample_data_loader.py` step and run it

## Your Environment

Followed the quick start guide's steps exactly

* Amunsen version used: 
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by nadamakram** [comment]
I am having the same issue too

**Comment by feng-tao** [comment]
will take a look. thanks for reporting.

**Comment by dorianj** [comment]
i'm debugging this, will post stuff as I find it

i changed the log line at `databuilder/loader/file_system_neo4j_csv_loader.py:160` to `        LOGGER.info('Creating file for {}: {}'.format(key, csv_record_dict.keys()))` and it gives:

`INFO:databuilder.loader.file_system_neo4j_csv_loader:Creating file for ('Stat', 6): dict_keys(['LABEL', 'KEY', 'stat_val:UNQUOTED', 'stat_name', 'start_epoch', 'end_epoch'])`

then later, when the exception is raised, that is trying to insert `stat_val` (without the `:UNQUOTED`), thus the error. I'm not clear yet whether it should have that unquoted in the file or not

**Comment by dorianj** [comment]
meant to mention -- this was caused (or possibly more accurately, revealed) by https://github.com/amundsen-io/amundsendatabuilder/pull/380

**Comment by feng-tao** [comment]
@HenryLiMN fixed are merged in databuilder, could you pull the latest master and retry?

**Comment by feng-tao** [comment]
feel free to reopen if the issue persists.

**Comment by HenryLiMN** [comment]
It worked! Thanks for the quick fix 🚀
