### ISSUE TITLE
Unable start up es_amundsen 

### ISSUE THREAD

**Issue by forestlzj** [amundsen-io/amundsen#806]
I am following the quickstart guide to startup docker images.  It raises blow error es_amundsen, others are fine.

```
[root@serv99 amundsen]# docker-compose -f docker-amundsen.yml up
Starting neo4j_amundsen ... done
Starting es_amundsen      ... done
Starting amundsenmetadata ... done
Starting amundsensearch   ... done
Starting amundsenfrontend ... done
Attaching to neo4j_amundsen, es_amundsen, amundsenmetadata, amundsensearch, amundsenfrontend
amundsenmetadata    | [2020-11-11 07:55:41 +0000] [1] [INFO] Starting gunicorn 20.0.4
neo4j_amundsen      | Changed password for user 'neo4j'.
amundsensearch      | [2020-11-11 07:55:41 +0000] [1] [INFO] Starting gunicorn 20.0.4
**es_amundsen         | Exception in thread "main" java.nio.file.AccessDeniedException: /tmp/elasticsearch-3637133116367293550**
es_amundsen         |   at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
es_amundsen         |   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
amundsenmetadata    | [2020-11-11 07:55:41 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
amundsensearch      | [2020-11-11 07:55:41 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
amundsensearch      | [2020-11-11 07:55:41 +0000] [1] [INFO] Using worker: sync
neo4j_amundsen      | Active database: amundsen.db
amundsenmetadata    | [2020-11-11 07:55:41 +0000] [1] [INFO] Using worker: sync
amundsensearch      | [2020-11-11 07:55:41 +0000] [8] [INFO] Booting worker with pid: 8
amundsensearch      | [2020-11-11 07:55:42 +0000] [9] [INFO] Booting worker with pid: 9
amundsenmetadata    | [2020-11-11 07:55:41 +0000] [8] [INFO] Booting worker with pid: 8
es_amundsen         |   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
amundsenmetadata    | [2020-11-11 07:55:41 +0000] [9] [INFO] Booting worker with pid: 9
neo4j_amundsen      | Directories in use:
neo4j_amundsen      |   home:         /var/lib/neo4j
neo4j_amundsen      |   config:       /var/lib/neo4j/conf
neo4j_amundsen      |   logs:         /var/log/neo4j
neo4j_amundsen      |   plugins:      /plugins
neo4j_amundsen      |   import:       /var/lib/neo4j/import
neo4j_amundsen      |   data:         /neo4j/data
neo4j_amundsen      |   certificates: /var/lib/neo4j/certificates
neo4j_amundsen      |   run:          /var/lib/neo4j/run
```

/tmp folder exists with mode 777.   

no es_amundsen image is running :
[root@serv99 /]# docker ps
```
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
e9c05e230a4c        amundsendev/amundsen-frontend:2.3.0   "gunicorn -w 2 --bin…"   30 minutes ago      Up 2 minutes        0.0.0.0:5000->5000/tcp                                     amundsenfrontend
cfa4f19dd0e6        amundsendev/amundsen-metadata:2.5.5   "gunicorn -w 2 --bin…"   31 minutes ago      Up 2 minutes        0.0.0.0:5002->5000/tcp                                     amundsenmetadata
09b9bb4bc683        amundsendev/amundsen-search:2.4.0     "gunicorn -w 2 --bin…"   31 minutes ago      Up 2 minutes        0.0.0.0:5001->5000/tcp                                     amundsensearch
92bb78892a21        neo4j:3.3.0                           "/docker-entrypoint.…"   4 weeks ago         Up 2 minutes        0.0.0.0:7474->7474/tcp, 7473/tcp, 0.0.0.0:7687->7687/tcp   neo4j_amundsen
```

## Expected Behavior

es_amundsen can be started up 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amunsen version used:   current master version
* Data warehouse stores:
* Deployment (k8s or native):  
```
docker --version
Docker version 19.03.13, build 4484c46d9d
```

* Link to your fork or repository:

**Comment by jornh** [comment]
The path `/tmp/elasticsearch-3637133116367293550` is referring to a path inside your Elasticsearch container not your host file system (the compose file  does not volume map the `/tmp` folder). 

Perhaps something is broken with your container image? I'd try doing a fresh pull of it. Perhaps with a never 6.x series version.  How does the ES container behave if you just run it alone with e.g.:

```
docker run --name elasticsearch  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:6.7.0
```

**Comment by forestlzj** [comment]
docker run --name elasticsearch  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:6.7.0
```
Exception in thread "main" java.nio.file.AccessDeniedException: /tmp/elasticsearch-12230778990403845544
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:692)
        at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:135)
        at java.base/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:172)
        at java.base/java.nio.file.Files.createTempDirectory(Files.java:1009)
        at org.elasticsearch.tools.launchers.Launchers.createTempDirectory(Launchers.java:66)
        at org.elasticsearch.tools.launchers.TempDirectory.main(TempDirectory.java:54)
```

**Comment by forestlzj** [comment]
The image is broken.  
It works after deleting and downloading again.
