### ISSUE TITLE
Unable to load sample data

### ISSUE THREAD

**Issue by forestlzj** [amundsen-io/amundsen#808]
## Expected Behavior
Sample data should be loaded successfully

## Current Behavior
I am following the guideline https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md , docker containers are up. when loading the sample data after with step:
```
$ python3 -m venv venv
 $ source venv/bin/activate  
 $ pip3 install -r requirements.txt
 $ python3 setup.py install
 $ python3 example/scripts/sample_data_loader.py
```

It raised error:

```
 python3 example/scripts/sample_data_loader.py

Traceback (most recent call last):
  File "example/scripts/sample_data_loader.py", line 285, in <module>
    'databuilder.models.table_stats.TableColumnStats')
  File "example/scripts/sample_data_loader.py", line 115, in run_csv_job
    publisher=Neo4jCsvPublisher()).launch()
  File "/home/app/amundsen/amundsendatabuilder/venv/lib64/python3.6/site-packages/amundsen_databuilder-4.0.3-py3.6.egg/databuilder/job/job.py", line 77, in launch
  File "/home/app/amundsen/amundsendatabuilder/venv/lib64/python3.6/site-packages/amundsen_databuilder-4.0.3-py3.6.egg/databuilder/job/job.py", line 67, in launch
  File "/home/app/amundsen/amundsendatabuilder/venv/lib64/python3.6/site-packages/amundsen_databuilder-4.0.3-py3.6.egg/databuilder/task/task.py", line 65, in run
  File "/home/app/amundsen/amundsendatabuilder/venv/lib64/python3.6/site-packages/amundsen_databuilder-4.0.3-py3.6.egg/databuilder/loader/file_system_neo4j_csv_loader.py", line 119, in load
  File "/usr/lib64/python3.6/csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/usr/lib64/python3.6/csv.py", line 151, in _dict_to_list
    + ", ".join([repr(x) for x in wrong_fields]))
ValueError: dict contains fields not in fieldnames: 'stat_val'

```

How to fix it?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amunsen version used: current master version
* Data warehouse stores:
* Deployment (k8s or native):  
Docker version 19.03.13, build 4484c46d9d
* Link to your fork or repository:

**Comment by lxlguy** [comment]
same issue as https://github.com/amundsen-io/amundsen/issues/803?
I realised i was not on master branch when i cloned the project and switching to master solved the issue.

**Comment by feng-tao** [comment]
the issue should be fixed in latest master. Please let us know if you still see the issue and feel free to reopen the issue.

**Comment by forestlzj** [comment]
fixed after getting the master
