### ISSUE TITLE
Not to able to connect to metadatasearch API call. 

### ISSUE THREAD

**Issue by NiravLangaliya** [amundsen-io/amundsen#809]
getting error when I try to get or post via metadata search API. 

**OS:** Running on Red Hat Linux 7 
**Python version:** 3.7.9 

` curl -X GET "http://localhost:5002/user" -H "accept: application/json"
`
![image](https://user-images.githubusercontent.com/13895686/98942987-d949d400-2514-11eb-854b-03f3a31a6080.png)

2020-11-12T12:50:01+0000.784 [INFO] __init__.create_app:83 (30353:MainThread) - Created app with config name metadata_service.config.LocalConfig
2020-11-12T12:50:01+0000.784 [INFO] __init__.create_app:84 (30353:MainThread) - Using backend metadata_service.proxy.neo4j_proxy.Neo4jProxy
 * Serving Flask app "metadata_service" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-11-12T12:50:01+0000.873 [INFO] _internal._log:122 (30353:MainThread) -  * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
2020-11-12T12:50:01+0000.874 [INFO] _internal._log:122 (30353:MainThread) -  * Restarting with stat
2020-11-12T12:50:02+0000.209 [INFO] __init__.create_app:83 (30359:MainThread) - Created app with config name metadata_service.config.LocalConfig
2020-11-12T12:50:02+0000.209 [INFO] __init__.create_app:84 (30359:MainThread) - Using backend metadata_service.proxy.neo4j_proxy.Neo4jProxy
2020-11-12T12:50:02+0000.298 [WARNING] _internal._log:122 (30359:MainThread) -  * Debugger is active!
2020-11-12T12:50:02+0000.299 [INFO] _internal._log:122 (30359:MainThread) -  * Debugger PIN: 156-831-455
2020-11-12T12:50:07+0000.960 [INFO] neo4j_proxy.__init__:69 (30359:Thread-2) - NEO4J endpoint: bolt://0.0.0.0:7687
2020-11-12T12:50:08+0000.005 [DEBUG] direct.connect:954 (30359:Thread-2) - [#0000]  C: <RESOLVE> Address(host='0.0.0.0', port=7687)
2020-11-12T12:50:08+0000.006 [DEBUG] direct._connect:830 (30359:Thread-2) - [#0000]  C: <OPEN> ('0.0.0.0', 7687)
2020-11-12T12:50:08+0000.006 [DEBUG] direct._secure:852 (30359:Thread-2) - [#776E]  C: <SECURE> 0.0.0.0
2020-11-12T12:50:08+0000.027 [INFO] _internal._log:122 (30359:Thread-2) - 127.0.0.1 - - [12/Nov/2020 12:50:08] "GET /user HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/neobolt/direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/flask/views.py", line 87, in view
    self = view.view_class(*class_args, **class_kwargs)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/api/user.py", line 30, in __init__
    self.client = get_proxy_client()
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/proxy/__init__.py", line 44, in get_proxy_client
    validate_ssl=validate_ssl)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/proxy/neo4j_proxy.py", line 76, in __init__
    trust=trust)  # type: Driver
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/neobolt/direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/neobolt/direct.py", line 859, in _secure
    raise error
neobolt.exceptions.SecurityError: Failed to establish secure connection to 'EOF occurred in violation of protocol (_ssl.c:1091)'

Metadata API Health check 

`curl -v http://localhost:5002/healthcheck`

![image](https://user-images.githubusercontent.com/13895686/98943532-abb15a80-2515-11eb-8312-1885df4a58af.png)

Neo4J version
![image](https://user-images.githubusercontent.com/13895686/98943098-ff6f7400-2514-11eb-9135-959a8f6d4d51.png)

I am able to run sample_data_loader.py script and able to load sample data into neo4j. 

![image](https://user-images.githubusercontent.com/13895686/98943359-5bd29380-2515-11eb-99fc-d7e89fe863bb.png)

I have also followed this https://github.com/neo4j/neo4j-python-driver/issues/331 
and modified neo4j_proxy.py  and didn't set METADATA_SVC_CONFIG_MODULE_CLASS so metadata_wsgi.py is using **metadata_service.config.LocalConfig**
![image](https://user-images.githubusercontent.com/13895686/98944016-63df0300-2516-11eb-83cf-8d61b7a65146.png)

**Comment by davcamer** [comment]
This configuration looks correct to me. I do have a couple of questions.

How are you running the metadata service? Could you try setting two environment variables in the run environment:
```
PROXY_ENCRYPTED=no
PROXY_VALIDATE_SSL=no
```

In the screenshot where you report the Neo4j version, it looks like you have connected with cypher-shell. Are you able to connect using the same address used in the metadata service configuration? I believe it is `bolt://0.0.0.0:7687` from the logs you posted.

How are you running Neo4j? In docker? 

This is the PR mentioned in Slack that aimed to support Neo4j 4.x: https://github.com/amundsen-io/amundsenmetadatalibrary/pull/139

**Comment by NiravLangaliya** [comment]
> bolt://0.0.0.0:7687



> This configuration looks correct to me. I do have a couple of questions.
> 
> How are you running the metadata service? Could you try setting two environment variables in the run environment:
> 
> ```
> PROXY_ENCRYPTED=no
> PROXY_VALIDATE_SSL=no
> ```
> 
> LocalConfig has code to read these variables for the Neo4j driver's encryption settings.
> 
> In the screenshot where you report the Neo4j version, it looks like you have connected with cypher-shell. Are you able to connect using the same address used in the metadata service configuration? I believe it is `bolt://0.0.0.0:7687` from the logs you posted.
> 
> How are you running Neo4j? In docker?
> 
> This is the PR mentioned in Slack that aimed to support Neo4j 4.x: [amundsen-io/amundsenmetadatalibrary#139](https://github.com/amundsen-io/amundsenmetadatalibrary/pull/139)

I am running metadata service from command line 

`/home/ec2-user/python_venv/amundsenmetadatalibrary/bin/python /home/ec2-user/amundsen/amundsenmetadatalibrary/metadata_service/metadata_wsgi.py`

where python version is 3.7 

```
udo /home/ec2-user/python_venv/amundsenmetadatalibrary/bin/python
Python 3.7.9 (default, Nov 11 2020, 13:45:41)
[GCC 4.8.5 20150623 (SuSE 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

I have changed and tried to run it but I am still getting same error.

PROXY_ENCRYPTED = False
PROXY_VALIDATE_SSL = False

![image](https://user-images.githubusercontent.com/13895686/99142792-665c6c80-267e-11eb-9e6d-b652b816afc7.png)

also I have already modified neo4j_proxy.py code so I think that should be make encrypted=False. 

![image](https://user-images.githubusercontent.com/13895686/99142884-306bb800-267f-11eb-8764-1ba223c72691.png)

I have installed neo4j from source and running on same machine where I have extracted Amundsen code.  ( not using docker for Neo4J and Amundsen code)

on your question. Am I able to connect to Neo4J at bolt://0.0.0.0:7687 ? yes, I am able to connect to it.

![image](https://user-images.githubusercontent.com/13895686/99142820-b0455280-267e-11eb-94fe-02d16d55e148.png)

Not with keeping `driver = GraphDatabase.driver(uri, auth=(user, password))`

![image](https://user-images.githubusercontent.com/13895686/99142850-f00c3a00-267e-11eb-86ba-01270c852de2.png)

but If I keep `driver = GraphDatabase.driver(uri, auth=(user, password),encrypted=False)` then I am able to connect it. 

![image](https://user-images.githubusercontent.com/13895686/99142879-277ae680-267f-11eb-9e3d-a3c17ae870c0.png)

**Comment by davcamer** [comment]
Hi again Nirav. I've just been trying the driver in a REPL locally as you showed in your second message. I am getting the same result.

I had asked about docker since while I was working on this change I was often accidentally not running the latest code. For me, that was because I was using docker-compose without the --build parameter.

I think this could be happening in your case as well. It still seems like the most likely explanation to me. There is some slim evidence in that the logs you posted the first time show the `trust=trust)` fragment appearing on line 76:
```
File "/home/ec2-user/python_venv/amundsenmetadatalibrary/lib/python3.7/site-packages/amundsen_metadata-2.5.5-py3.7.egg/metadata_service/proxy/neo4j_proxy.py", line 76, in init
trust=trust) # type: Driver
```
But, in the screenshots from your editor this appears on line 78. Note also that the path in the stack trace is under the venv's site-packages, rather than `/home/ec2-user/amundsen/amundsenmetadatalibrary/metadata_service/proxy/neo4j_proxy.py` where we would expect to find your edited file.

I realize you might have pasted logs from before you added the `= False` in line 69 and 70, but it was something I wanted to check. That is why I suggested setting the environment variables: even if the unedited code is for some reason running, the environment variables should turn off encryption.

The non-docker-compose approach to ensure you are running your latest code is documented in the README and requires running the module set up after code edits. Something like:
```
$ python3 setup.py install
$ python3 metadata_service/metadata_wsgi.py
```

It would be great to have a local environment set up that would do "hot-reloading" of the python code as it is edited, or even that wouldn't require installing the module between runs, but I am not experienced enough with Python web dev to advise on that.

**Comment by NiravLangaliya** [comment]
I will check it again but for now , I have installed Neo4j 3.5 and it is working.

**Comment by jornh** [comment]
@NiravLangaliya since you got it working, and you didn't return with anything actionable for the project I suggest you close this as resolved.

**Comment by NiravLangaliya** [comment]
yes we can close it as I have change Neo4J version to 3.5 and the code is working and we will internally checking that why it was not working with Neo4j version >= 4.x.x
