### ISSUE TITLE
Not able to access frontend UI

### ISSUE THREAD

**Issue by NiravLangaliya** [amundsen-io/amundsen#822]
I am getting error while trying to access Frontend UI at via localhost:5000. I am not running Lyft Amundsen from docker. 

I have installed Neo4j and Elasticsearch separately and also running all services from source. 

Could you please help me to resolve this issue? 

![image](https://user-images.githubusercontent.com/13895686/100095226-2ec0a200-2e80-11eb-86ae-3966e59224b5.png)

 * Debug mode: off
2020-11-24T12:14:23+0000.115 [INFO] _internal._log:113 (27308:MainThread) -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-11-24T12:14:31+0000.682 [ERROR] app.log_exception:1761 (27308:Thread-1) - Exception on / [GET]
Traceback (most recent call last):
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/amundsen_frontend-2.3.0-py3.6.egg/amundsen_application/api/__init__.py", line 19, in index
    return render_template("index.html", env=ENVIRONMENT)  # pragma: no cover
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2020-11-24T12:14:31+0000.685 [INFO] _internal._log:113 (27308:Thread-1) - 127.0.0.1 - - [24/Nov/2020 12:14:31] "GET / HTTP/1.1" 500 -
2020-11-24T12:14:32+0000.291 [ERROR] app.log_exception:1761 (27308:Thread-2) - Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/amundsen_frontend-2.3.0-py3.6.egg/amundsen_application/api/__init__.py", line 19, in index
    return render_template("index.html", env=ENVIRONMENT)  # pragma: no cover
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2020-11-24T12:14:32+0000.291 [INFO] _internal._log:113 (27308:Thread-2) - 127.0.0.1 - - [24/Nov/2020 12:14:32] "GET /favicon.ico HTTP/1.1" 500 -

**Comment by dorianj** [comment]
Have you built the JS front-end via `npm run build` inside `static`?

**Comment by NiravLangaliya** [comment]
**npm install**
npm WARN eslint-config-airbnb@18.1.0 req
uires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react-hooks@^2.5.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@14.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-typescript@8.0.2 requires a peer of @typescript-eslint/eslint-plugin@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 4185 packages in 22.196s

222 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

Also I have attached **npm run build**  result. 
[npm_run_build_result.txt](https://github.com/amundsen-io/amundsen/files/5591520/npm_run_build_result.txt)

**Comment by dorianj** [comment]
that looks good -- so just confirming that you ran that, and afterwards re-running `wsgi` still fails with that error? (you might have to restart wsgi, I don't remember). if so, what command are you running `wsgi` with?

**Comment by NiravLangaliya** [comment]
After I ran npm command , I have started wsgi service again. 

` /home/ec2-user/python_venv/amundsenfrontendlibrary/bin/python amundsen_application/wsgi.py`


Registering post_exec action_log entry_point: logging_action_log = amundsen_application.log.action_log_callback:logging_action_log
2020-11-24T17:00:59+0000.376 [INFO] __init__.create_app:58 (12319:MainThread) - Created app with config name amundsen_application.config.LocalConfig
2020-11-24T17:00:59+0000.377 [INFO] __init__.create_app:59 (12319:MainThread) - Using metadata service at http://0.0.0.0:5002
2020-11-24T17:00:59+0000.377 [INFO] __init__.create_app:60 (12319:MainThread) - Using search service at http://0.0.0.0:5001
 * Serving Flask app "amundsen_application" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-11-24T17:00:59+0000.414 [INFO] _internal._log:113 (12319:MainThread) -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-11-24T17:01:31+0000.838 [ERROR] app.log_exception:1761 (12319:Thread-1) - Exception on / [GET]
Traceback (most recent call last):
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/amundsen_frontend-2.3.0-py3.6.egg/amundsen_application/api/__init__.py", line 19, in index
    return render_template("index.html", env=ENVIRONMENT)  # pragma: no cover
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2020-11-24T17:01:31+0000.840 [INFO] _internal._log:113 (12319:Thread-1) - 127.0.0.1 - - [24/Nov/2020 17:01:31] "GET / HTTP/1.1" 500 -
2020-11-24T17:01:32+0000.676 [ERROR] app.log_exception:1761 (12319:Thread-2) - Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/amundsen_frontend-2.3.0-py3.6.egg/amundsen_application/api/__init__.py", line 19, in index
    return render_template("index.html", env=ENVIRONMENT)  # pragma: no cover
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ec2-user/python_venv/amundsenfrontendlibrary/lib64/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2020-11-24T17:01:32+0000.676 [INFO] _internal._log:113 (12319:Thread-2) - 127.0.0.1 - - [24/Nov/2020 17:01:32] "GET /favicon.ico HTTP/1.1" 500 -

**Comment by dorianj** [comment]
did you run `setup.py install` previously? I'm not sure, but maybe you need to run that again after building the FE.

i personally run `wsgi.py` with `PYTHONPATH=.` to avoid the need to re-installing the package

**Comment by NiravLangaliya** [comment]
it worked. thank you for helping me out.
