### ISSUE TITLE
Missing dependency to google auth in example/scripts/sample_bigquery_metadata.py

### ISSUE THREAD

**Issue by tloszabno** [amundsen-io/amundsen#887]
I just cloned your repo run commands from the instruction:
```
python3 -m venv venv
source venv/bin/activate  
pip3 install -r requirements.txt
python3 setup.py install
``` 
inside folder `amundsen/amundsendatabuilder`.

all work well, but when I try to run: `python3 example/scripts/sample_bigquery_metadata.py`

I receive:

```
Traceback (most recent call last):
  File "example/scripts/sample_bigquery_metadata.py", line 14, in <module>
    from databuilder.extractor.bigquery_metadata_extractor import BigQueryMetadataExtractor
  File "<frozen zipimport>", line 259, in load_module
  File "/home/tomaszlos/workspace/data/tmp/amundsen/amundsendatabuilder/venv/lib/python3.8/site-packages/amundsen_databuilder-4.0.4-py3.8.egg/databuilder/extractor/bigquery_metadata_extractor.py", line 11, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/tomaszlos/workspace/data/tmp/amundsen/amundsendatabuilder/venv/lib/python3.8/site-packages/amundsen_databuilder-4.0.4-py3.8.egg/databuilder/extractor/base_bigquery_extractor.py", line 11, in <module>
ModuleNotFoundError: No module named 'google'
``` 

I am able to fix that by adding:
```
google-cloud-bigquery
google-api-python-client
google-auth-httplib2
google-auth-oauthlib
```
to `requirements.txt`

**Comment by feng-tao** [comment]
@tloszabno gcp requires to install extra deps (https://github.com/amundsen-io/amundsendatabuilder/blob/master/setup.py#L39-L43) .Do you do python setup.py install[bigquery] ?

**Comment by tloszabno** [comment]
Hello, @feng-tao, thanks for your aswer! 

`python setup.py install` - yes

`python setup.py install[bigquery]` - no

 I just followed with instruction on that page: https://www.amundsen.io/amundsen/installation/
Maybe there (in manual) should be brief information, that if sb use other loaders need to install additional dependencies with the command you've provided?

**Comment by feng-tao** [comment]
Feel free to improve the doc with pr. But I am going to close this issue now.
