### ISSUE TITLE
Tableau dashboard extractor shows TypeError when user token has insufficient privilege

### ISSUE THREAD

**Issue by shuichiro-makigaki** [amundsen-io/amundsen#911]
Tableau dashboard extractor shows TypeError when the user token has insufficient privilege for projects or dashboards.

```
Traceback (most recent call last):
  File "tableau_data_loader.py", line 344, in <module>
    run_tableau_metadata_job()
  File "tableau_data_loader.py", line 188, in run_tableau_metadata_job
    job.launch()
  File "amundsendatabuilder/databuilder/job/job.py", line 76, in launch
    raise e
  File "amundsendatabuilder/databuilder/job/job.py", line 66, in launch
    self.task.run()
  File "amundsendatabuilder/databuilder/task/task.py", line 75, in run
    record = self.extractor.extract()
  File "amundsendatabuilder/databuilder/extractor/dashboard/tableau/tableau_dashboard_extractor.py", line 109, in extract
    record = self._extractor.extract()
  File "amundsendatabuilder/databuilder/extractor/dashboard/tableau/tableau_dashboard_utils.py", line 127, in extract
    record = next(self._iterator)
  File "amundsendatabuilder/databuilder/extractor/dashboard/tableau/tableau_dashboard_extractor.py", line 45, in execute
    'dashboard_name': TableauDashboardUtils.sanitize_workbook_name(workbook['name']),
  File "amundsendatabuilder/databuilder/extractor/dashboard/tableau/tableau_dashboard_utils.py", line 65, in sanitize_workbook_name
    return re.sub(r'(\/|\')', '', workbook_name)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

## Expected Behavior

These forbidden dashboards should be ignored with some warning messages.

## Current Behavior

Raise the exception and stop running.

## Possible Solution

Tableau API returns `null` for dashboard name or project name when the user token does not have access privilege for the dashboard or the project.
As a result, a workbook object, for example, is:

```python
{
    'id': '71615743-8806-e86c-7c2e-49a8db04989e',
    'name': None,
    'createdAt': '2020-01-15T02:52:46Z',
    'description': None,
    'projectName': None,
    'projectVizportalUrlId': '1386',
    'vizportalUrlId': '10835'
}
```

The sanitizers in `TableauDashboardUtils` will raise `TypeError` when the value is `None`.
If these names are `None`, we should ignore them and shows some warnings.
A patch is ready: https://github.com/shuichiro-makigaki/amundsendatabuilder/tree/ignore-invisible-workbooks

## Steps to Reproduce

1. Revoke permissions for some Tableau projects from the user token
2. Run example script `example_tableau_data_loader.py`

## Context

Users can not import Tableau dashboards.

## Your Environment

* Amunsen version used: amundsendatabuilder 4.1.0
* Data warehouse stores: Elasticsearch and Neo4j
* Deployment (k8s or native): AWS ECS
* Link to your fork or repository: https://github.com/shuichiro-makigaki/amundsendatabuilder/tree/ignore-invisible-workbooks

**Comment by feng-tao** [comment]
I am not super familiar on tableau. But if you have a pr for the fix, let us know.
