### ISSUE TITLE
Amundsen Quickstart multiple issues

### ISSUE THREAD

**Issue by niklahun** [amundsen-io/amundsen#971]
Hi All, 
Following the very first step of the official quickstart guide: 
[https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#bootstrap-a-default-version-of-amundsen-using-docker](https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#bootstrap-a-default-version-of-amundsen-using-docker)

_(venv) PS C:\Users\D\amundsen> git clone --recursive git@github.com:amundsen-io/amundsen.git
Cloning into 'amundsen'...
Enter passphrase for key '/c/Users/D/.ssh/id_ed25519':
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository._

Please make sure you have the correct access rights
and the repository exists.

I can clone other projects from github without issues. 
I tried downloading the repo itself, but the amundsendatabuilder submodule is empty, so i downloaded that as well. 

All goes fine until the last step: python3 example/scripts/sample_data_loader.py

```
File "C:\Users\D\amundsen\amundsen-master\amundsen-master\amundsendatabuilder\venv\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 232, in perform_request
    response = self.pool.urlopen(
  File "C:\Users\D\amundsen\amundsen-master\amundsen-master\amundsendatabuilder\venv\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "C:\Users\D\amundsen\amundsen-master\amundsen-master\amundsendatabuilder\venv\lib\site-packages\urllib3\util\retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\D\amundsen\amundsen-master\amundsen-master\amundsendatabuilder\venv\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Users\D\amundsen\amundsen-master\amundsen-master\amundsendatabuilder\venv\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\D\amundsen\amundsen-master\amundsen-master\amundsendatabuilder\venv\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Python38\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Users\D\amundsen\amundsen-master\amundsen-master\amundsendatabuilder\venv\lib\site-packages\urllib3\connection.py", line 184, in connect
    conn = self._new_conn()
  File "C:\Users\D\amundsen\amundsen-master\amundsen-master\amundsendatabuilder\venv\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001905117DA60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
Traceback (most recent call last):
  File "C:\Users\D\amundsen\amundsen-master\amundsen-master\amundsendatabuilder\venv\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

```

**Now Amundsen is stuck in a limbo; if i search it finds nothing, but if i check in neo4j or use the direct [link ](http://localhost:5000/table_detail/gold/dynamo/test_schema/test_table2)there are objects.

What am i doing wrong?**

**Comment by niklahun** [comment]
> I've got the same issue with the quickstart quide. Following works for me
> 
> `git clone --recursive https://github.com/amundsen-io/amundsen.git`
> 
> Please make sure that you add the
> 
> `--recursive`
> 
> flag to get all subfolders.

as you can see i do exactly this :)
But the clone itself fails first - also shouldn't downloading a project yield the same result as cloning it?

**Comment by lestremm** [comment]
I've assumed that you've downloaded the amundsendatabuilder manually. Maybe that was my fault but manually download sounds not like a good approach. Maybe you try to checkout the git repo with my suggested command above a second time? If this wouldn't help you can run the example/scripts/sample_data_loader.py script with an IDE like PyCharm an debug ist. May this helps us to find the error.
